BEGIN TRANSACTION;

INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (7000, 2, NULL); -- Eolian
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (7001, 0, NULL); -- Erdeen
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (7002, 3, NULL); -- Pyrophor
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (7003, 4, NULL); -- Undine

END TRANSACTION;