BEGIN TRANSACTION;

INSERT INTO MONSTER_APPEARING ([MONSTER_ID], [NO_APPEARING_FROM], [NO_APPEARING_TO], [DICE_NUMBER], [DIE_FACES], [MODIFIER], [MULTIPLIER], [PROBABILITY], [ENCOUNTER_LOCATION_ID]) VALUES (703, NULL, NULL, 1, 4, NULL, NULL, NULL, 0); -- Eolian
INSERT INTO MONSTER_APPEARING ([MONSTER_ID], [NO_APPEARING_FROM], [NO_APPEARING_TO], [DICE_NUMBER], [DIE_FACES], [MODIFIER], [MULTIPLIER], [PROBABILITY], [ENCOUNTER_LOCATION_ID]) VALUES (704, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0); -- Erdeen
INSERT INTO MONSTER_APPEARING ([MONSTER_ID], [NO_APPEARING_FROM], [NO_APPEARING_TO], [DICE_NUMBER], [DIE_FACES], [MODIFIER], [MULTIPLIER], [PROBABILITY], [ENCOUNTER_LOCATION_ID]) VALUES (705, NULL, NULL, 1, 6, 1, NULL, NULL, 0); -- Pyrophor
INSERT INTO MONSTER_APPEARING ([MONSTER_ID], [NO_APPEARING_FROM], [NO_APPEARING_TO], [DICE_NUMBER], [DIE_FACES], [MODIFIER], [MULTIPLIER], [PROBABILITY], [ENCOUNTER_LOCATION_ID]) VALUES (706, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0); -- Undine


END TRANSACTION;