BEGIN TRANSACTION;

INSERT INTO MONSTER_TREASURE ([MONSTER_ID], [TREASURE_CLASS_ID], [MULTIPLIER], [MULTIPLIER_DICE_NUM], [MULTIPLIER_DIE_FACES], [LOCATION_ID], [TREASURE_COMPONENT_ID]) VALUES (7000, NULL, NULL, NULL, NULL, NULL, NULL); -- Nil - Eolian
INSERT INTO MONSTER_TREASURE ([MONSTER_ID], [TREASURE_CLASS_ID], [MULTIPLIER], [MULTIPLIER_DICE_NUM], [MULTIPLIER_DIE_FACES], [LOCATION_ID], [TREASURE_COMPONENT_ID]) VALUES (7001, NULL, NULL, NULL, NULL, NULL, NULL); -- Special - Erdeen
INSERT INTO MONSTER_TREASURE ([MONSTER_ID], [TREASURE_CLASS_ID], [MULTIPLIER], [MULTIPLIER_DICE_NUM], [MULTIPLIER_DIE_FACES], [LOCATION_ID], [TREASURE_COMPONENT_ID]) VALUES (7002, NULL, NULL, NULL, NULL, NULL, NULL); -- Nil - Pyrophor
INSERT INTO MONSTER_TREASURE ([MONSTER_ID], [TREASURE_CLASS_ID], [MULTIPLIER], [MULTIPLIER_DICE_NUM], [MULTIPLIER_DIE_FACES], [LOCATION_ID], [TREASURE_COMPONENT_ID]) VALUES (7003, NULL, NULL, NULL, NULL, NULL, NULL); -- Nil - Undine

COMMIT TRANSACTION;