BEGIN TRANSACTION;

INSERT INTO MONSTER_MOVEMENT ([MONSTER_ID], [MOVEMENT_TYPE], [MOVEMENT_FACTOR], [MANEUVERABILITY_CLASS], [MOVEMENT_VARIANT]) VALUES (7000, 1, 36, 0, NULL); -- Eolian
INSERT INTO MONSTER_MOVEMENT ([MONSTER_ID], [MOVEMENT_TYPE], [MOVEMENT_FACTOR], [MANEUVERABILITY_CLASS], [MOVEMENT_VARIANT]) VALUES (7001, NULL, 18, NULL, NULL); -- Erdeen
INSERT INTO MONSTER_MOVEMENT ([MONSTER_ID], [MOVEMENT_TYPE], [MOVEMENT_FACTOR], [MANEUVERABILITY_CLASS], [MOVEMENT_VARIANT]) VALUES (7002, NULL, 12, NULL, NULL); -- Pyrophor
INSERT INTO MONSTER_MOVEMENT ([MONSTER_ID], [MOVEMENT_TYPE], [MOVEMENT_FACTOR], [MANEUVERABILITY_CLASS], [MOVEMENT_VARIANT]) VALUES (7002, 1, 36, 2, NULL); -- Pyrophor
INSERT INTO MONSTER_MOVEMENT ([MONSTER_ID], [MOVEMENT_TYPE], [MOVEMENT_FACTOR], [MANEUVERABILITY_CLASS], [MOVEMENT_VARIANT]) VALUES (7003, NULL, 9, NULL, NULL); -- Undine
INSERT INTO MONSTER_MOVEMENT ([MONSTER_ID], [MOVEMENT_TYPE], [MOVEMENT_FACTOR], [MANEUVERABILITY_CLASS], [MOVEMENT_VARIANT]) VALUES (7003, 2, 24, NULL, NULL); -- Undine

END TRANSACTION;