BEGIN TRANSACTION;

INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (703, 1025); -- Eolian
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (703, 1026); -- Eolian
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (703, 1028); -- Eolian
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (704, 1026); -- Erdeen
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (705, 1028); -- Pyrophor
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (706, 1025); -- Undine

COMMIT TRANSACTION;