BEGIN TRANSACTION;

INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (7000, 14); -- Elemental of Chaos, Air, Eolian
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (7000, 15);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (7001, 16); -- Elemental of Chaos, Earth, Erdeen
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (7001, 17);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (7002, 12); -- Elemental of Chaos, Fire, Pyrophor
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (7003, 18); -- Elemental of Chaos, Water, Undine

COMMIT TRANSACTION;