BEGIN TRANSACTION;

INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4000, 4, 'aspis', 'Cow', 'Aspis, Cow', 'Aspis, Cow', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4001, 4, 'aspis', 'Drone', 'Aspis, Drone', 'Aspis, Drone', 2, 11, 12);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4002, 4, 'aspis', 'Larva', 'Aspis, Larva', 'Aspis, Larva', 2, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4003, 4, 'beastman', 'Beastman', 'Beastman', 'Beastman', 1, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4004, NULL, 'beetle', 'Death Watch', 'Beetle, Death Watch', 'Beetle, Death Watch', 1, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4005, NULL, 'beetle', 'Slicer', 'Beetle, Slicer', 'Beetle, Slicer', 2, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4006, NULL, 'beetle', 'Stink', 'Beetle, Stink', 'Beetle, Stink', 2, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4007, 4, 'bonesnap', 'Bonesnapper', 'Bonesnapper', 'Bonesnapper', 2, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4008, 4, 'booka', 'Booka', 'Booka', 'Booka', 3, 11, 12);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4009, 4, 'browbuck', 'Brownie, Buckawn', 'Brownie, Buckawn', 'Brownie, Buckawn', 2, 8, 12);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4010, 4, 'browquic', 'Brownie, Quickling', 'Brownie, Quickling', 'Brownie, Quickling', 1, 13, 18);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4011, 4, 'crysmist', 'Crystalmist', 'Crystalmist', 'Crystalmist', 3, 0, 1);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4012, 4, 'dragoegh', 'Dragon (Oerth), Greyhawk', 'Dragon (Oerth), Greyhawk', 'Dragon (Oerth), Greyhawk', 1, 19, 20);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4013, 4, 'drgnflgi', 'Adult', 'Dragonfly, Giant, Adult', 'Dragonfly, Giant, Adult', 2, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4014, 4, 'drgnflgi', 'Larva (Nymph)', 'Dragonfly, Giant, Larva (Nymph)', 'Dragonfly, Giant, Larva (Nymph)', 2, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4015, 4, 'drgonnel', 'Dragonnel', 'Dragonnel', 'Dragonnel', 1, 2, 4);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4016, 4, 'elfgruga', 'Elf, Grugach', 'Elf, Grugach', 'Elf, Grugach', 1, 11, 18);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4017, 4, 'elfvalle', 'Elf, Valley', 'Elf, Valley', 'Elf, Valley', 1, 14, 20);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4018, 4, 'golenecr', 'Golem, Necrophidius', 'Golem, Necrophidius', 'Golem, Necrophidius', 1, 10, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4019, 4, 'grelwild', 'Grell, Wild', 'Grell, Wild', 'Grell, Wild', 2, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4020, 4, 'grung', 'Grung', 'Grung', 'Grung', 3, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4021, NULL, 'hobgnork', 'Hobgoblin, Norker', 'Hobgoblin, Norker', 'Hobgoblin, Norker', 2, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4022, 4, 'horgar', 'Horgar', 'Horgar', 'Horgar', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4023, 6, 'hounyeth', 'Hound, Yeth', 'Hound, Yeth', 'Hound, Yeth', 1, NULL, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4024, 4, 'iguagian', 'Iguana, Giant', 'Iguana, Giant', 'Iguana, Giant', 2, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4025, 4, 'ingundi', 'Ingundi', 'Ingundi', 'Ingundi', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4026, 4, 'kech', 'Kech', 'Kech', 'Kech', 2, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4027, 4, 'kyussson', 'Kyuss, Son of', 'Kyuss, Son of', 'Kyuss, Son of', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4028, 4, 'mite', 'Mite', 'Mite', 'Mite', 2, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4029, 4, 'mite', 'Snyad (Pestie)', 'Mite, Snyad (Pestie)', 'Mite, Snyad (Pestie)', 3, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4030, 4, 'needlman', 'Needleman', 'Needleman', 'Needleman', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4031, 4, 'plancaoe', 'Kampfult', 'Plant, Carnivorous (Oerth), Kampfult', 'Plant, Carnivorous (Oerth), Kampfult', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4032, 4, 'plancaoe', 'Polyp, Giant', 'Plant, Carnivorous (Oerth), Polyp, Giant', 'Plant, Carnivorous (Oerth), Polyp, Giant', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4033, 4, 'plancavc', 'Plant, Carnivorous, Vampire Cactus', 'Plant, Carnivorous, Vampire Cactus', 'Plant, Carnivorous, Vampire Cactus', 1, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4034, 4, 'ratoerth', 'Camprat', 'Rat (Oerth), Camprat', 'Rat (Oerth), Camprat', 4, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4035, 4, 'ratoerth', 'Vapor Rat', 'Rat (Oerth), Vapor Rat', 'Rat (Oerth), Vapor Rat', 2, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4036, 4, 'raven', 'Giant', 'Raven/Crow, Giant', 'Raven/Crow, Giant', 2, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4037, 4, 'raven', 'Huge', 'Raven/Crow, Huge', 'Raven/Crow, Huge', 2, 2, 4);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4038, 4, 'raven', 'Ordinary', 'Raven/Crow, Ordinary', 'Raven/Crow, Ordinary', 4, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4039, 4, 'scarecro', 'Scarecrow', 'Scarecrow', 'Scarecrow', 1, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4040, 4, 'shadslow', 'Shadow, Slow', 'Shadow, Slow', 'Shadow, Slow', 2, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4041, 4, 'skulk', 'Skulk', 'Skulk', 'Skulk', 2, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4042, 4, 'snail', 'Flail', 'Snail, Flail', 'Snail, Flail', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4043, 4, 'snail', 'Sea', 'Snail, Sea', 'Snail, Sea', 1, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4044, 4, 'taer', 'Taer', 'Taer', 'Taer', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4045, 4, 'tentamor', 'Tentamort', 'Tentamort', 'Tentamort', 2, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4046, 4, 'turtgian', 'Sea, Giant', 'Turtle, Giant, Sea, Giant', 'Turtle, Giant, Sea, Giant', 3, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4047, 4, 'turtgian', 'Snapping, Giant', 'Turtle, Giant, Snapping, Giant', 'Turtle, Giant, Snapping, Giant', 3, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4048, 4, 'tyrg', 'Tyrg', 'Tyrg', 'Tyrg', 2, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4049, 4, 'wolfmist', 'Wolf, Mist', 'Wolf, Mist', 'Wolf, Mist', 1, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4050, 4, 'wraioert', 'Soul Beckoner', 'Wraith (Oerth), Soul Beckoner', 'Wraith (Oerth), Soul Beckoner', 2, 13, 13);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4051, 4, 'wraioert', 'Swordwraith', 'Wraith (Oerth), Swordwraith', 'Wraith (Oerth), Swordwraith', 2, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (4052, 4, 'zygom', 'Zygom', 'Zygom', 'Zygom', 2, 0, NULL);

COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------

-- BEGIN TRANSACTION;

-- INSERT INTO MONSTER_PLANE ([MONSTER_ID], [PLANE_ID]) VALUES (7, 35); -- Pit fiend

-- COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------

BEGIN TRANSACTION;

INSERT INTO MONSTER_UNDEAD ([MONSTER_ID], [TURNED_AS]) VALUES (4027,  14);	--Kyuss, Son of
INSERT INTO MONSTER_UNDEAD ([MONSTER_ID], [TURNED_AS]) VALUES (4040,  6);	--Shadow, Slow
INSERT INTO MONSTER_UNDEAD ([MONSTER_ID], [TURNED_AS]) VALUES (4050,  18);	--Wraith (Oerth), Soul Beckoner
INSERT INTO MONSTER_UNDEAD ([MONSTER_ID], [TURNED_AS]) VALUES (4051,  NULL);	--Wraith (Oerth), Swordwraith

COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------

-- BEGIN TRANSACTION;

-- INSERT INTO MONSTER_ELEMENTAL ([MONSTER_ID], [ELEMENT_ID]) VALUES (166, 0);		-- Air elemental

-- COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------

BEGIN TRANSACTION;

INSERT INTO MONSTER_DRAGON ([MONSTER_ID], [TYPE]) VALUES (4012, NULL);
INSERT INTO MONSTER_DRAGON ([MONSTER_ID], [TYPE]) VALUES (4015, NULL);

COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------