BEGIN TRANSACTION;

INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1000, 4, 'aspis', 'Cow', 'Aspis, Cow', 'Aspis, Cow', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1001, 4, 'aspis', 'Drone', 'Aspis, Drone', 'Aspis, Drone', 2, 11, 12);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1002, 4, 'aspis', 'Larva', 'Aspis, Larva', 'Aspis, Larva', 2, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1003, 4, 'beastman', 'Beastman', 'Beastman', 'Beastman', 1, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1004, NULL, 'beetle', 'Death Watch', 'Beetle, Death Watch', 'Beetle, Death Watch', 1, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1005, NULL, 'beetle', 'Slicer', 'Beetle, Slicer', 'Beetle, Slicer', 2, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1006, NULL, 'beetle', 'Stink', 'Beetle, Stink', 'Beetle, Stink', 2, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1007, 4, 'bonesnap', 'Bonesnapper', 'Bonesnapper', 'Bonesnapper', 2, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1008, 4, 'booka', 'Booka', 'Booka', 'Booka', 3, 11, 12);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1009, 4, 'browbuck', 'Brownie, Buckawn', 'Brownie, Buckawn', 'Brownie, Buckawn', 2, 8, 12);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1010, 4, 'browquic', 'Brownie, Quickling', 'Brownie, Quickling', 'Brownie, Quickling', 1, 13, 18);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1011, 4, 'crysmist', 'Crystalmist', 'Crystalmist', 'Crystalmist', 3, 0, 1);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1012, 4, 'dragoegh', 'Dragon (Oerth), Greyhawk', 'Dragon (Oerth), Greyhawk', 'Dragon (Oerth), Greyhawk', 1, 19, 20);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1013, 4, 'drgnflgi', 'Adult', 'Dragonfly, Giant, Adult', 'Dragonfly, Giant, Adult', 2, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1014, 4, 'drgnflgi', 'Larva (Nymph)', 'Dragonfly, Giant, Larva (Nymph)', 'Dragonfly, Giant, Larva (Nymph)', 2, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1015, 4, 'drgonnel', 'Dragonnel', 'Dragonnel', 'Dragonnel', 1, 2, 4);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1016, 4, 'elfgruga', 'Elf, Grugach', 'Elf, Grugach', 'Elf, Grugach', 1, 11, 18);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1017, 4, 'elfvalle', 'Elf, Valley', 'Elf, Valley', 'Elf, Valley', 1, 14, 20);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1018, 4, 'golenecr', 'Golem, Necrophidius', 'Golem, Necrophidius', 'Golem, Necrophidius', 1, 10, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1019, 4, 'grelwild', 'Grell, Wild', 'Grell, Wild', 'Grell, Wild', 2, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1020, 4, 'grung', 'Grung', 'Grung', 'Grung', 3, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1021, NULL, 'hobgnork', 'Hobgoblin, Norker', 'Hobgoblin, Norker', 'Hobgoblin, Norker', 2, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1022, 4, 'horgar', 'Horgar', 'Horgar', 'Horgar', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1023, 6, 'hounyeth', 'Hound, Yeth', 'Hound, Yeth', 'Hound, Yeth', 1, NULL, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1024, 4, 'iguagian', 'Iguana, Giant', 'Iguana, Giant', 'Iguana, Giant', 2, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1025, 4, 'ingundi', 'Ingundi', 'Ingundi', 'Ingundi', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1026, 4, 'kech', 'Kech', 'Kech', 'Kech', 2, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1027, 4, 'kyussson', 'Kyuss, Son of', 'Kyuss, Son of', 'Kyuss, Son of', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1028, 4, 'mite', 'Mite', 'Mite', 'Mite', 2, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1029, 4, 'mite', 'Snyad (Pestie)', 'Mite, Snyad (Pestie)', 'Mite, Snyad (Pestie)', 3, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1030, 4, 'needlman', 'Needleman', 'Needleman', 'Needleman', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1031, 4, 'plancaoe', 'Kampfult', 'Plant, Carnivorous (Oerth), Kampfult', 'Plant, Carnivorous (Oerth), Kampfult', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1032, 4, 'plancaoe', 'Polyp, Giant', 'Plant, Carnivorous (Oerth), Polyp, Giant', 'Plant, Carnivorous (Oerth), Polyp, Giant', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1033, 4, 'plancavc', 'Plant, Carnivorous, Vampire Cactus', 'Plant, Carnivorous, Vampire Cactus', 'Plant, Carnivorous, Vampire Cactus', 1, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1034, 4, 'ratoerth', 'Camprat', 'Rat (Oerth), Camprat', 'Rat (Oerth), Camprat', 4, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1035, 4, 'ratoerth', 'Vapor Rat', 'Rat (Oerth), Vapor Rat', 'Rat (Oerth), Vapor Rat', 2, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1036, 4, 'raven', 'Giant', 'Raven/Crow, Giant', 'Raven/Crow, Giant', 2, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1037, 4, 'raven', 'Huge', 'Raven/Crow, Huge', 'Raven/Crow, Huge', 2, 2, 4);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1038, 4, 'raven', 'Ordinary', 'Raven/Crow, Ordinary', 'Raven/Crow, Ordinary', 4, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1039, 4, 'scarecro', 'Scarecrow', 'Scarecrow', 'Scarecrow', 1, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1040, 4, 'shadslow', 'Shadow, Slow', 'Shadow, Slow', 'Shadow, Slow', 2, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1041, 4, 'skulk', 'Skulk', 'Skulk', 'Skulk', 2, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1042, 4, 'snail', 'Flail', 'Snail, Flail', 'Snail, Flail', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1043, 4, 'snail', 'Sea', 'Snail, Sea', 'Snail, Sea', 1, 1, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1044, 4, 'taer', 'Taer', 'Taer', 'Taer', 1, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1045, 4, 'tentamor', 'Tentamort', 'Tentamort', 'Tentamort', 2, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1046, 4, 'turtgian', 'Sea, Giant', 'Turtle, Giant, Sea, Giant', 'Turtle, Giant, Sea, Giant', 3, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1047, 4, 'turtgian', 'Snapping, Giant', 'Turtle, Giant, Snapping, Giant', 'Turtle, Giant, Snapping, Giant', 3, 0, NULL);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1048, 4, 'tyrg', 'Tyrg', 'Tyrg', 'Tyrg', 2, 5, 7);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1049, 4, 'wolfmist', 'Wolf, Mist', 'Wolf, Mist', 'Wolf, Mist', 1, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1050, 4, 'wraioert', 'Soul Beckoner', 'Wraith (Oerth), Soul Beckoner', 'Wraith (Oerth), Soul Beckoner', 2, 13, 13);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1051, 4, 'wraioert', 'Swordwraith', 'Wraith (Oerth), Swordwraith', 'Wraith (Oerth), Swordwraith', 2, 8, 10);
INSERT INTO MONSTER ([ID], [CAMPAIGN_SETTINGS_ID], [EXT_KEY], [EXT_SUBKEY], [NAME], [DISPLAY_NAME], [FREQUENCY_ID], [INTELLIGENCE_FROM], [INTELLIGENCE_TO]) VALUES (1052, 4, 'zygom', 'Zygom', 'Zygom', 'Zygom', 2, 0, NULL);

COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------

-- BEGIN TRANSACTION;

-- INSERT INTO MONSTER_PLANE ([MONSTER_ID], [PLANE_ID]) VALUES (7, 35); -- Pit fiend

-- COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------

BEGIN TRANSACTION;

INSERT INTO MONSTER_UNDEAD ([MONSTER_ID], [TURNED_AS]) VALUES (1027,  14);	--Kyuss, Son of
INSERT INTO MONSTER_UNDEAD ([MONSTER_ID], [TURNED_AS]) VALUES (1040,  6);	--Shadow, Slow
INSERT INTO MONSTER_UNDEAD ([MONSTER_ID], [TURNED_AS]) VALUES (1050,  18);	--Wraith (Oerth), Soul Beckoner
INSERT INTO MONSTER_UNDEAD ([MONSTER_ID], [TURNED_AS]) VALUES (1051,  NULL);	--Wraith (Oerth), Swordwraith

COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------

-- BEGIN TRANSACTION;

-- INSERT INTO MONSTER_ELEMENTAL ([MONSTER_ID], [ELEMENT_ID]) VALUES (166, 0);		-- Air elemental

-- COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------

BEGIN TRANSACTION;

INSERT INTO MONSTER_DRAGON ([MONSTER_ID], [TYPE]) VALUES (1012, NULL);
INSERT INTO MONSTER_DRAGON ([MONSTER_ID], [TYPE]) VALUES (1015, NULL);

COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------