BEGIN TRANSACTION;

INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4000, 514); -- Aspis, Cow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4001, 514); -- Aspis, Drone
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4002, 514); -- Aspis, Larva
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4003, 513); -- Beastman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4003, 514); -- Beastman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4004, 514); -- Beetle, Death Watch
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4005, 514); -- Beetle, Slicer
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4006, 514); -- Beetle, Stink
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4007, 514); -- Bonesnapper
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4008, 514); -- Booka
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4008, 1025); -- Booka
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4009, 514); -- Brownie, Buckawn
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4010, 1026); -- Brownie, Quickling
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4010, 1028); -- Brownie, Quickling
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4011, 514); -- Crystalmist
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4012, 257); -- Dragon (Oerth), Greyhawk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4012, 258); -- Dragon (Oerth), Greyhawk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4013, 514); -- Dragonfly, Giant, Adult
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4014, 514); -- Dragonfly, Giant, Larva (Nymph)
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4015, 514); -- Dragonnel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4015, 516); -- Dragonnel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4016, 1026); -- Elf, Grugach
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4017, 1026); -- Elf, Valley
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4018, 514); -- Golem, Necrophidius
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4019, 516); -- Grell, Wild
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4020, 260); -- Grung
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4021, 1028); -- Hobgoblin, Norker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4022, 514); -- Horgar
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4023, 516); -- Hound, Yeth
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4024, 514); -- Iguana, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4025, 1028); -- Ingundi
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4026, 516); -- Kech
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4027, 1028); -- Kyuss, Son of
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4028, 260); -- Mite
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4029, 514); -- Mite, Snyad (Pestie)
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4030, 514); -- Needleman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4031, 514); -- Plant, Carnivorous (Oerth), Kampfult
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4032, 516); -- Plant, Carnivorous (Oerth), Polyp, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4033, 514); -- Plant, Carnivorous, Vampire Cactus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4034, 514); -- Rat (Oerth), Camprat
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4035, 1026); -- Rat (Oerth), Vapor Rat
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4036, 514); -- Raven/Crow, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4036, 516); -- Raven/Crow, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4037, 514); -- Raven/Crow, Huge
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4037, 516); -- Raven/Crow, Huge
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4038, 514); -- Raven/Crow, Ordinary
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4039, 260); -- Scarecrow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4039, 516); -- Scarecrow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4039, 1028); -- Scarecrow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4040, 1028); -- Shadow, Slow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4041, 1028); -- Skulk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4042, 514); -- Snail, Flail
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4043, 514); -- Snail, Sea
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4044, 514); -- Taer
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4045, 514); -- Tentamort
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4046, 514); -- Turtle, Giant, Sea, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4047, 514); -- Turtle, Giant, Snapping, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4048, 1026); -- Tyrg
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4049, 257); -- Wolf, Mist
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4050, 516); -- Wraith (Oerth), Soul Beckoner
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4051, 260); -- Wraith (Oerth), Swordwraith
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4052, 516); -- Zygom

COMMIT TRANSACTION;