BEGIN TRANSACTION;

INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (1, 'Forgotten Realms');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (2, 'Ravenloft');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (3, 'Dark Sun');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (4, 'Greyhawk');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (5, 'Spelljammer');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (6, 'Planescape');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (7, 'Mystara');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (8, 'Al-Qadim (Forgotten Realms)');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (9, 'Maztica (Forgotten Realms)');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (10, 'Dragonlance');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (11, 'Red Steel (Mystara)');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (12, 'Lankhmar');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (13, 'Birthright');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (14, 'Kara-Tur (Forgotten Realms)');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (15, 'Masque of the Red Death (Ravenloft)');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (16, 'The Horde (Forgotten Realms)');
INSERT INTO CAMPAIGN_SETTINGS ([ID], [DESCRIPTION]) VALUES (17, 'Alternity');

COMMIT TRANSACTION;

-------------------------------------------------------------------------------------------------------------

BEGIN TRANSACTION;

INSERT INTO [EDITION] ([ACRONYM], [DESCRIPTION]) VALUES ('Adnd2.0', 'Advanced Dungeons & Dragons 2nd Edition');

COMMIT TRANSACTION;

-------------------------------------------------------------------------------------------------------------

BEGIN TRANSACTION;

INSERT INTO [DIE] ([ID], [ACRONYM], [DESCRIPTION]) VALUES (4, 'd4', 'Four-faced die');
INSERT INTO [DIE] ([ID], [ACRONYM], [DESCRIPTION]) VALUES (6, 'd6', 'Six-faced die');
INSERT INTO [DIE] ([ID], [ACRONYM], [DESCRIPTION]) VALUES (8, 'd8', 'Eight-faced die');
INSERT INTO [DIE] ([ID], [ACRONYM], [DESCRIPTION]) VALUES (10, 'd10', 'Ten-faced die');
INSERT INTO [DIE] ([ID], [ACRONYM], [DESCRIPTION]) VALUES (12, 'd12', 'Twelve-faced die');
INSERT INTO [DIE] ([ID], [ACRONYM], [DESCRIPTION]) VALUES (20, 'd20', 'Twenty-faced die');
INSERT INTO [DIE] ([ID], [ACRONYM], [DESCRIPTION]) VALUES (100, 'd100', 'One hundred-faced die');

COMMIT TRANSACTION;

-------------------------------------------------------------------------------------------------------------

BEGIN TRANSACTION;

INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(0, 'Tribal');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(1, 'Brood');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(2, 'Entourage');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(3, 'Soltary');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(4, 'Swarm');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(5, 'Flock');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(6, 'Pack');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(7, 'Band');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(8, 'Family');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(9, 'Squad');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(10, 'Family group');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(11, 'Pride');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(12, 'Group');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(13, 'Herd');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(14, 'Small pack');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(15, 'School');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(16, 'Clan');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(17, 'Family liar');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(18, 'Patch');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(19, 'Pair');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(20, 'Loose band');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(21, 'Multicellular');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(22, 'Mated pair');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(23, 'Caliphate');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(24, 'Khanate');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(25, 'Sultanate');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(26, 'Padishate');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(27, 'Amirate');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(28, 'Hunting group');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(29, 'Platoon');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(30, 'Ship');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(31, 'Military');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(32, 'Dictatorship');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(33, 'Monarchy');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(34, 'Colony');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(35, 'Guild');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(36, 'Hive');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(37, 'Covery');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(38, 'Community');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(39, 'Small herd');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(40, 'Individual');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(41, 'Gens');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(42, 'City');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(43, 'Communal');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(44, 'Trio');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(45, 'With other lawful evil creatures');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(46, 'Mixed evil');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(47, 'With feeders');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(48, 'Nest');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(49, 'Cluster');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(50, 'Stand');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(51, 'Bed');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(52, 'Roving band');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(53, 'Herd leader');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(54, 'Grove');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(55, 'Pod');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(56, 'Nation');
INSERT INTO ORGANISATION ([ID], [DESCRIPTION]) VALUES(57, 'Cooperative');

COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------

BEGIN TRANSACTION;

INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(0, 'Carnivore');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(1, 'Omnivore');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(2, 'Herbivore');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(3, 'Magic');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(4, 'Insectivore');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(5, 'Scavenger');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(6, 'Psionic energy');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(7, 'Varies');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(8, 'Vegetarian');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(9, 'Special');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(10, 'Wind');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(11, 'Minerals');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(12, 'Fire');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(13, 'Clean water');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(14, 'Air');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(15, 'Clouds');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(16, 'Earth');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(17, 'Metal');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(18, 'Water');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(19, 'Gem');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(20, 'Any combustible');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(21, 'Any liquid');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(22, 'Emotions');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(23, 'Corpses');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(24, 'Blood');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(25, 'Human Flesh');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(26, 'Mental energy');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(27, 'Assimilation');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(28, 'Brains');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(29, 'Man-eater');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(30, 'Heat');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(31, 'Moisture');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(32, 'Dweomer');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(33, 'Living plasma');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(34, 'Sun');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(35, 'Soil');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(36, 'Memories');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(37, 'Any');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(38, 'Metalavore');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(39, 'Living beings');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(40, 'Fish');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(41, 'Photosynthesis');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(42, 'Plankton');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(43, 'Books');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(44, 'Magical metal');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(45, 'Carrion');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(46, 'Life energy');
INSERT INTO DIET ([ID], [DESCRIPTION]) VALUES(47, 'Panic feeling');

COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------

BEGIN TRANSACTION;

INSERT INTO DRAGON_TYPE ([ID], [NAME]) VALUES (0, 'Chromatic');
INSERT INTO DRAGON_TYPE ([ID], [NAME]) VALUES (1, 'Gem');
INSERT INTO DRAGON_TYPE ([ID], [NAME]) VALUES (2, 'Metallic');
INSERT INTO DRAGON_TYPE ([ID], [NAME]) VALUES (3, 'Other');
INSERT INTO DRAGON_TYPE ([ID], [NAME]) VALUES (4, 'Dragonet');

COMMIT TRANSACTION;

-----------------------------------------------------------------------------------------------------------

