BEGIN TRANSACTION;

INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (1, 1); -- Aarakocra
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (2, 2); -- Aboleth
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (3, 0); -- Ankheg
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (4, 0); -- Arcane
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (5, 3); -- Argos
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (6, 1); -- Aurumvorax
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (7, 0); -- Pit fiend
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (8, 0); -- Black abishai
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (9, 0); -- Green abishai
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (10, 0); -- Red abishai
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (11, 2); -- Banshee
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (12, 1); -- Lesser basilisk
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (13, 1); -- Greater basilisk
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (14, 1); -- Dracolisk
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (15, 2); -- Common bat
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (16, 2); -- Large bat
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (17, 2); -- Huge bat
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (18, 0); -- Azmyth
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (20, 0); -- Sinister
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (21, 1); -- Black bear
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (22, 1); -- Brown bear
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (23, 1); -- Cave bear
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (24, 1); -- Polar bear
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (25, 1); -- Bombardier
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (26, 2); -- Boring beetle
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (27, 2); -- Fire beetle
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (28, 0); -- Rhinoceros beetle
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (29, 0); -- Stag beetle
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (30, 0); -- Water beetle
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (31, 1); -- Behir
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (32, 0); -- Beholder
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (33, 0); -- Death kiss
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (34, 1); -- Eye of the deep
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (35, 1); -- Gauth
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (36, 1); -- Spectator
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (37, 1); -- Undead beholder
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (38, 0); -- Hive mother
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (39, 1); -- Director
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (40, 2); -- Examiner
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (41, 1); -- Lensman
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (42, 0); -- Overseer
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (43, 0); -- Watcher
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (72, 2); -- Brain mole
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (75, 2); -- Brownie
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (76, 4); -- Killmoulis
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (77, 0); -- Bugbear
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (78, 0); -- Bulette
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (79, 0); -- Bullywug
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (80, 0); -- Carrion crawler
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (81, 1); -- Cheetah
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (82, 0); -- Jaguar
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (83, 0); -- Leopard
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (84, 1); -- Common lion
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (86, 1); -- Spotted lion
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (87, 2); -- Giant lynx
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (88, 2); -- Wild tiger
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (89, 2); -- Smilodon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (90, 0); -- Domestic cat
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (91, 0); -- Wild cat
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (92, 0); -- Elven cat
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (93, 1); -- Catoblepas
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (94, 2); -- Cave fisher
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (95, 1); -- Centaur
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (96, 0); -- Giant centipede
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (97, 0); -- Huge centipede
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (98, 0); -- Megalo-centipede
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (99, 0); -- Tunnel centipede
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (100, 0); -- Chimera
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (101, 0); -- Gorgimera
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (102, 2); -- Cloaker
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (103, 0); -- Cockatrice
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (104, 0); -- Pyrolisk
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (105, 0); -- Couatl
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (106, 0); -- Crabman
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (107, 0); -- Crawling Claw
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (108, 1); -- Crocodile
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (109, 1); -- Giant crocodile
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (110, 0); -- Giant crab
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (111, 0); -- Giant crayfish
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (112, 0); -- Crypt Thing
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (113, 0); -- Death Knight
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (114, 0); -- Deepspawn
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (115, 1); -- Ankylosaurus
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (116, 1); -- Deinonychus
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (117, 1); -- Diplodocus
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (118, 1); -- Elasmosaurus
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (119, 1); -- Lambeosaurus
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (120, 1); -- Pteranodon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (121, 1); -- Stegosaurus
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (122, 1); -- Triceratops
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (123, 1); -- Tyrannosaurus
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (124, 0); -- Displacer Beast
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (125, 0); -- Wild dog
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (126, 0); -- War dog
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (127, 0); -- Blink dog
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (128, 2); -- Death dog
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (129, 0); -- Mood dog
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (130, 0); -- Dolphin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (131, 0); -- Doppleganger
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (132, 2); -- Dracolich
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (133, 0); -- Black Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (134, 0); -- Blue Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (135, 0); -- Green Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (136, 0); -- Red Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (137, 0); -- White Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (138, 0); -- Amethyst Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (139, 0); -- Crystal Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (140, 0); -- Emerald Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (141, 0); -- Sapphire Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (142, 0); -- Topaz Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (143, 0); -- Brass Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (144, 0); -- Bronze Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (145, 0); -- Copper Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (146, 0); -- Gold Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (147, 0); -- Silver Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (148, 0); -- Brown Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (149, 0); -- Cloud Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (150, 0); -- Deep Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (151, 0); -- Mercury Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (152, 0); -- Mist Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (154, 0); -- Steel Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (155, 0); -- Yellow Dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (156, 0); -- Dragon turtle
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (157, 0); -- Faerie dragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (158, 1); -- Firedrake
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (159, 1); -- Pseudodragon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (161, 0); -- Dryad
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (162, 0); -- Hill dwarf
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (163, 0); -- Mountain dwarf
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (164, 2); -- Derro
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (165, 0); -- Duergar
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (166, 0); -- Air elemental
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (167, 0); -- Earth elemental
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (168, 0); -- Fire elemental
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (169, 0); -- Water elemental
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (170, 0); -- Sylph
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (171, 0); -- Aerial servant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (172, 7); -- Pech
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (173, 0); -- Sandling
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (174, 0); -- Salamander
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (175, 0); -- Fire Snake
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (176, 0); -- Nereid
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (177, 0); -- Water weird
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (178, 0); -- Tempest
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (179, 0); -- Skriaxit
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (181, 1); -- Mammoth
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (182, 0); -- Mastodon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (183, 1); -- Oliphant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (184, 0); -- Elf
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (185, 0); -- Aquatic elf
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (189, 0); -- Eyewing
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (190, 2); -- Feyr
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (191, 0); -- Great Feyr
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (214, 0); -- Giant frog
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (215, 0); -- Killer frog
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (216, 0); -- Poisonous frog
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (217, 0); -- Violet fungus
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (218, 0); -- Shrieker
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (219, 0); -- Phycomid
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (220, 0); -- Ascomoid
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (221, 0); -- Gas spore
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (222, 1); -- Galeb Duhr
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (223, 2); -- Gargantua Reptilian
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (224, 0); -- Gargantua Humanoid
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (225, 0); -- Gargantua Insectoid
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (226, 0); -- Gargoyle
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (227, 0); -- Margoyle
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (228, 1); -- Djinni
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (229, 1); -- Dao
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (230, 1); -- Efreeti
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (231, 1); -- Marid
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (232, 1); -- Jann
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (233, 2); -- Ghost
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (234, 2); -- Ghoul
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (235, 2); -- Lacedon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (236, 2); -- Ghast
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (237, 0); -- Cloud giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (238, 0); -- Cyclopskin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (239, 0); -- Cyclops
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (240, 1); -- Desert giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (241, 2); -- Ettin giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (242, 0); -- Firbolg giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (243, 0); -- Fire giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (244, 1); -- Fog giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (245, 0); -- Formorian giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (246, 0); -- Frost giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (247, 0); -- Hill giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (248, 1); -- Jungle giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (249, 0); -- Mountain giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (250, 1); -- Reef giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (251, 0); -- Stone giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (252, 0); -- Storm giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (253, 0); -- Verbeeg giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (254, 1); -- Wood giant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (256, 1); -- Giff
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (258, 0); -- Gith pirate
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (259, 0); -- Githyanki
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (260, 0); -- Githzerai
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (262, 0); -- Tenebrous worm
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (263, 2); -- Gnoll
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (264, 2); -- Flind
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (265, 0); -- Rock gnome
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (266, 0); -- Svirfneblin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (267, 0); -- Tinker
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (268, 1); -- Forest gnome
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (269, 0); -- Gnome spriggan
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (270, 2); -- Goblin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (271, 0); -- Stone Golem
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (272, 0); -- Iron Golem
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (273, 0); -- Flesh Golem
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (275, 0); -- Bone Golem
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (276, 0); -- Doll Golem
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (277, 0); -- Golem gargoyle
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (278, 0); -- Glass Golem
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (279, 0); -- Golem necrophidus
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (280, 0); -- Scarecrow
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (281, 0); -- Caryatid
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (282, 0); -- Juggernaut
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (283, 0); -- Stone guardian
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (284, 1); -- Gorgon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (285, 0); -- Grell Worker
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (286, 0); -- Grell Philosopher
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (287, 0); -- Grell Patriarch
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (288, 2); -- Gremlin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (289, 1); -- Fremlin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (290, 2); -- Galltrit
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (291, 0); -- Mite
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (292, 0); -- Snyad
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (293, 0); -- Jermlaine
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (294, 0); -- Griffon
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (295, 2); -- Grimlock
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (296, 1); -- Grippli
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (297, 2); -- Annis
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (298, 2); -- Green Hag
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (299, 2); -- Sea Hag
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (300, 1); -- Hairfoot
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (301, 1); -- Tallfellow
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (302, 1); -- Stout
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (303, 1); -- Harpy
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (304, 0); -- Lesser hatori
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (305, 0); -- Greater hatori
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (306, 0); -- Haunt
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (307, 0); -- Hell Hound
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (308, 0); -- Heucuva
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (309, 0); -- Hippocampus
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (310, 1); -- Hippogriff
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (311, 0); -- Hobgoblin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (312, 0); -- Homonculus
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (313, 0); -- Hook Horror
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (314, 1); -- Draft horse
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (315, 1); -- Heavy horse
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (316, 1); -- Medium horse
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (317, 1); -- Light horse
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (318, 1); -- Pony
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (319, 1); -- Wild horse
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (320, 1); -- Riding horse
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (321, 1); -- Mule
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (346, 0); -- Hydra
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (347, 0); -- Lernaean
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (348, 0); -- Pyrohydra
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (349, 0); -- Cryohydra
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (350, 0); -- Imp
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (351, 0); -- Quasit
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (352, 0); -- Fire Mephit
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (353, 0); -- Ice Mephit
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (354, 0); -- Lava Mephit
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (355, 0); -- Mist Mephit
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (356, 0); -- Smoke Mephit
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (357, 0); -- Steam Mephit
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (386, 1); -- Velvet ants swarm
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (387, 1); -- Grasshoppers swarm
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (388, 1); -- Locust swarm
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (389, 0); -- Adult Intellect Devourer
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (390, 7); -- Larva Intellect Devourer
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (391, 0); -- Invisible Stalker
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (392, 1); -- Ixitxachitl
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (393, 0); -- Jackalwere
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (394, 0); -- Kenku
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (395, 0); -- Ki-rin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (396, 1); -- Kirre
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (397, 2); -- Kobold
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (398, 2); -- Urd
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (399, 2); -- Kuo-toa
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (400, 0); -- Lamia
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (401, 0); -- Noble Lamia
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (402, 1); -- Lesser Lammasu
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (403, 1); -- Greater Lammasu
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (404, 0); -- Giant leech
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (405, 0); -- Throat leech
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (406, 0); -- Swarm leech
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (407, 0); -- Leprechaun
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (408, 0); -- Leucrotta
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (409, 2); -- Lich
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (411, 0); -- Living Wall
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (412, 1); -- Fire lizard
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (413, 1); -- Giant lizard
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (414, 1); -- Minotaur lizard
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (415, 1); -- Subterranean lizard
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (416, 0); -- Lizard Man
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (417, 0); -- Lizard King
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (418, 0); -- Locathah
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (419, 0); -- Lurker
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (420, 0); -- Trapper
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (421, 0); -- Forest Trapper
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (422, 0); -- Lesser seawolf
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (423, 0); -- Greater seawolf
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (424, 2); -- Werebat
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (425, 4); -- Werebear
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (426, 0); -- Wereboar
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (427, 4); -- Werefox
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (428, 4); -- Wererat
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (429, 1); -- Wereraven
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (430, 4); -- Weretiger
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (431, 4); -- Werewolf
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (462, 1); -- Camel
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (463, 1); -- Cattle
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (464, 1); -- Buffalo
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (465, 1); -- Antelope
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (466, 1); -- Sheep
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (490, 0); -- Manscorpion
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (491, 0); -- Manticore
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (492, 0); -- Medusa
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (493, 0); -- Greater Medusa
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (494, 0); -- Maedar
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (495, 0); -- Glyptar
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (496, 0); -- Merman
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (497, 0); -- Mimic
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (498, 0); -- Killer Mimic
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (499, 0); -- Mind Flayer
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (500, 2); -- Minotaur
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (501, 2); -- Crimson Death
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (502, 2); -- Vampiric Mist
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (503, 0); -- Brown Mold
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (504, 0); -- Russet Mold
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (505, 0); -- Yellow Mold
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (506, 0); -- Mold Man
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (507, 2); -- Mongrelman
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (508, 2); -- Morkoth
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (509, 1); -- Muckdweller
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (510, 0); -- Mudman
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (511, 2); -- Mummy
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (512, 2); -- Mummy Greater
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (513, 1); -- Myconid
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (514, 1); -- Guardian Naga
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (515, 2); -- Spirit Naga
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (516, 0); -- Water Naga
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (517, 0); -- Dark Naga
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (518, 0); -- Neogi
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (519, 0); -- Neogi Great Old Master
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (520, 0); -- Nightmare
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (521, 1); -- Nymph
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (522, 4); -- NULL
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (523, 0); -- Ogre
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (524, 0); -- Ogre Mage
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (525, 0); -- Merrow
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (526, 0); -- Half-Ogre
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (527, 0); -- Ogrillion
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (528, 0); -- Olive Slime
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (529, 0); -- Olive Slime Creature
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (530, 2); -- Mustard Jelly
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (531, 2); -- Stunjelly
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (532, 0); -- Ochre Jelly
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (533, 0); -- Gray Ooze
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (534, 0); -- Crystal Ooze
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (535, 0); -- Gelatinous Cube
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (536, 0); -- Green Slime
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (537, 0); -- Slithering Tracker
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (538, 2); -- Orc
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (539, 2); -- Orog
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (540, 0); -- Otyugh
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (541, 0); -- Neo-Otyugh
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (543, 1); -- Pegasus
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (544, 1); -- Peryton
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (545, 0); -- Phantom
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (546, 0); -- Phoenix
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (547, 0); -- Piercer
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (548, 1); -- Choke Creeper
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (549, 1); -- Mantrap
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (550, 0); -- Retch Plant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (551, 0); -- Snapper Saw
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (552, 0); -- Thornslinger
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (553, 1); -- Tri-Flower Frond
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (554, 0); -- Yellow Musk Creeper
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (555, 0); -- Yellow Musk Zombie
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (556, 1); -- Hangman tree
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (557, 0); -- Kelpie
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (558, 0); -- Obliviax
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (559, 0); -- Quickwood
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (560, 0); -- Shambling mound
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (561, 0); -- Strangleweed
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (562, 1); -- Giant Sundew
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (563, 1); -- Thorny
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (564, 2); -- Poltergeist
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (565, 0); -- Black Pudding
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (566, 0); -- White Pudding
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (567, 0); -- Brown Pudding
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (568, 0); -- Dun Pudding
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (569, 0); -- Quaggoth
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (570, 2); -- Rakshasa
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (571, 2); -- Greater Rakshasa
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (572, 2); -- Giant Rat
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (573, 2); -- Osquip
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (574, 1); -- Remorhaz
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (575, 2); -- Revenant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (576, 1); -- Roc
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (577, 7); -- Roper
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (578, 2); -- Rust Monster
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (579, 2); -- Sahuagin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (580, 0); -- Satyr
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (581, 0); -- Korred
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (582, 0); -- Large Scorpion
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (583, 0); -- Huge Scorpion
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (584, 0); -- Giant Scorpion
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (585, 1); -- Sea Lion
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (588, 10); -- Lesser Shedu
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (589, 10); -- Greater Shedu
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (590, 0); -- Sirine
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (591, 0); -- Skeleton
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (592, 0); -- Skeleton Animal
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (593, 0); -- Skeleton Monster
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (594, 0); -- Giant Skeleton
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (595, 0); -- Skeleton Warrior
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (596, 0); -- Red Slaad
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (597, 0); -- Blue Slaad
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (598, 0); -- Giant Slug
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (599, 1); -- Amphisbaena
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (600, 1); -- Boalisk
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (601, 1); -- Constrictor
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (602, 1); -- Giant constrictor
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (603, 1); -- Heway
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (604, 1); -- Poisonous Snake
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (605, 1); -- Giant Poisonous Snake
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (606, 1); -- Giant Sea Snake
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (607, 1); -- Spitting Snake
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (608, 0); -- Winged snake
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (610, 1); -- Androsphinx
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (611, 1); -- Criosphinx
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (612, 1); -- Gynosphinx
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (613, 1); -- Hieracosphinx
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (614, 0); -- Hairy Spider
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (615, 0); -- Large Spider
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (616, 0); -- Huge Spider
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (617, 0); -- Giant Spider
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (618, 0); -- Phase Spider
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (619, 0); -- Sword Spider
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (620, 0); -- Gargantuan Spider
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (621, 1); -- Sprite
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (622, 1); -- Sea sprite
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (623, 2); -- Pixie
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (624, 1); -- Nixie
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (625, 2); -- Atomie
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (626, 2); -- Grig
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (627, 0); -- Giant squid
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (628, 0); -- Kraken
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (629, 2); -- Stirge
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (631, 0); -- Swanmay
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (632, 0); -- Bird maiden
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (633, 0); -- Tabaxi
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (634, 4); -- Tabaxi Lord
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (635, 0); -- Male Tako
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (636, 0); -- Female Tako
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (637, 0); -- Balor
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (638, 0); -- Marilith
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (639, 11); -- Tarrasque
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (640, 2); -- Tasloi
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (641, 0); -- Thought-Eater
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (642, 12); -- Thri-Kreen
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (643, 0); -- Titan
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (644, 0); -- Giant Toad
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (645, 0); -- Fire Toad
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (646, 1); -- Ice Toad
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (647, 0); -- Poisonous Toad
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (648, 0); -- Treant
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (649, 1); -- Triton
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (650, 0); -- Troglodyte
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (651, 2); -- Troll
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (652, 0); -- Two-headed Troll
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (653, 1); -- Freshwater Troll
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (654, 2); -- Saltwater Troll
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (655, 0); -- Desert Troll
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (656, 2); -- Spectral Troll
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (657, 0); -- Giant Troll
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (658, 0); -- Ice Troll
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (660, 0); -- Umber Hulk
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (661, 0); -- Vodyanoi
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (662, 1); -- Unicorn
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (663, 0); -- Black Urchin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (664, 0); -- Green Urchin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (665, 0); -- Red Urchin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (666, 0); -- Silver Urchin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (667, 0); -- Yellow Urchin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (668, 1); -- Land Urchin
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (669, 2); -- Vampire
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (670, 1); -- Wemic
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (671, 0); -- Common Whale
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (672, 0); -- Giant Whale
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (673, 0); -- Leviathan
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (674, 0); -- Killer Whale
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (675, 0); -- Narwhal Whale
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (676, 2); -- Wight
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (677, 2); -- Will o'wisp
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (678, 0); -- Wolf
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (679, 0); -- Worg
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (680, 0); -- Dire Wolf
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (681, 0); -- Winter Wolf
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (682, 0); -- Wolfwere
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (683, 0); -- Purple Worm
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (684, 0); -- Giant Bloodworm
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (685, 0); -- Bookworm
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (686, 0); -- Rot Grub
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (687, 2); -- Wraith
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (689, 0); -- Xorn
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (690, 0); -- Xaren
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (691, 1); -- Yeti
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (692, 0); -- Yuan-ti
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (693, 0); -- Histachii
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (694, 0); -- Least Yugoloth
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (695, 0); -- Lesser Yugoloth
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (696, 0); -- Greater Yugoloth
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (697, 0); -- Zaratan
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (698, 2); -- Zombie
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (699, 2); -- Zombie Monster
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (700, 2); -- Ju-ju Zombie
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (701, 2); -- Zombie Lord
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES (702, 2); -- Sea Zombie

INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(19, 2); -- Night hunter
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(19, 0);
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(73, 0); -- Broken one
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(73, 2);
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(74, 0); -- Greater broken one
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(74, 2);
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(85, 5); -- Mountain lion
INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(85, 6);
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(146, NULL); -- Gold Dragon
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(153, NULL); -- Shadow Dragon
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(160, NULL); -- Dragonne
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(180, NULL); -- African elephant
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(186, NULL); -- Drow
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(187, NULL); -- Drider
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(188, NULL); -- Ettercap
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(192, NULL); -- Barracuda
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(193, NULL); -- Giant carp
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(194, NULL); -- Giant catfish
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(195, NULL); -- Dragonfish
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(196, NULL); -- Electric eel
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(197, NULL); -- Giant eel
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(198, NULL); -- Marine eel
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(199, NULL); -- Weed eel
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(200, NULL); -- Giant gar
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(201, NULL); -- Lamprey
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(202, NULL); -- Giant lamprey
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(203, NULL); -- Land lamprey
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(204, NULL); -- Manta ray
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(205, NULL); -- Giant pike
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(206, NULL); -- Piranha
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(207, NULL); -- Giant piranha
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(208, NULL); -- Pungi ray
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(209, NULL); -- Quipper
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(210, NULL); -- Giant sea horse
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(211, NULL); -- Shark
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(212, NULL); -- Giant shark
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(213, NULL); -- Sting ray
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(255, NULL); -- Gibberling
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(257, NULL); -- Gith
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(261, NULL); -- Moth
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(322, NULL); -- Aborigine/Caveman
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(323, NULL); -- Adventurer
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(324, NULL); -- Bandit/Brigand
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(325, NULL); -- Barbarian/Nomad
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(326, NULL); -- Berserker/Dervish
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(327, NULL); -- Farmer/Herder
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(328, NULL); -- Gentry
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(329, NULL); -- Knight
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(330, NULL); -- Mercenary
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(331, NULL); -- Merchant Sailor/Fisherman
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(332, NULL); -- Merchant/Trader
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(333, NULL); -- Middle class human
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(334, NULL); -- Peasant/Serf
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(335, NULL); -- Pilgrim
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(336, NULL); -- Pirate/Buccaneer
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(337, NULL); -- Police/Constabulary
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(338, NULL); -- Priest
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(339, NULL); -- Sailor
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(340, NULL); -- Slaver
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(341, NULL); -- Soldier
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(342, NULL); -- Thief/Thug
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(343, NULL); -- Tradesman/Craftsman
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(344, NULL); -- Tribesman
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(345, NULL); -- Wizard
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(358, NULL); -- Giant Ant
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(359, NULL); -- Giant Lion Ant
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(360, NULL); -- Aratha
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(361, NULL); -- Cow Aspis
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(362, NULL); -- Drone Aspis
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(363, NULL); -- Larva Aspis
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(364, NULL); -- Assassin Bug
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(365, NULL); -- Worker bee
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(366, NULL); -- Soldier bee
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(367, NULL); -- Bumblebee
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(368, NULL); -- Cave cricket
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(369, NULL); -- Giant dragonfly
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(370, NULL); -- Larva dragonfly
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(371, NULL); -- Ear seeker
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(372, NULL); -- Firefriend
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(373, NULL); -- Bluebottle
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(374, NULL); -- Horsefly
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(375, NULL); -- Fyrefly
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(376, NULL); -- Horax
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(377, NULL); -- Giant Hornet
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(378, NULL); -- Pernicon
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(379, NULL); -- Praying Mantis
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(380, NULL); -- King Giant Harvester
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(381, NULL); -- Queen Giant Harvester
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(382, NULL); -- Soldier Giant Harvester
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(383, NULL); -- Worker Giant Harvester
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(384, NULL); -- Giant tick
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(385, NULL); -- Giant wasp
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(410, NULL); -- Demilich
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(432, NULL); -- Carnivorous ape
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(433, NULL); -- Wild Baboon
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(434, NULL); -- Badger
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(435, NULL); -- Banderlog
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(436, NULL); -- Bhaergala
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(437, NULL); -- Wild boar
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(438, NULL); -- Chattur
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(439, NULL); -- Cooshee
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(440, NULL); -- Dakon
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(441, NULL); -- Debbi
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(442, NULL); -- Goat
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(443, NULL); -- Gorilla
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(444, NULL); -- Hsing-sing
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(445, NULL); -- Hyena
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(446, NULL); -- Jackal
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(447, NULL); -- Losel
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(448, NULL); -- Monkey Spider
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(450, NULL); -- Black porcupine
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(451, NULL); -- Brown porcupine
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(452, NULL); -- Rothe
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(453, NULL); -- Skunk
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(454, NULL); -- Sleek
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(455, NULL); -- Wild Stag
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(456, NULL); -- Stench Kow
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(457, NULL); -- Taer
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(458, NULL); -- Tyrg
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(459, NULL); -- Warthog
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(460, NULL); -- Weasel
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(461, NULL); -- Wolverine
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(467, NULL); -- Beaver
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(468, NULL); -- Chipmunk
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(469, NULL); -- Ermine
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(470, NULL); -- Ferret
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(471, NULL); -- Fox
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(472, NULL); -- Gopher
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(473, NULL); -- Hedgehog
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(474, NULL); -- Mink
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(475, NULL); -- Mole
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(476, NULL); -- Monkey
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(477, NULL); -- Mouse
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(478, NULL); -- Muskrat
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(479, NULL); -- Opossum
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(480, NULL); -- Otter
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(481, NULL); -- Sea Otter
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(482, NULL); -- Giant Otter
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(483, NULL); -- Domestic Pig
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(484, NULL); -- Wild Pig
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(485, NULL); -- Rabbit
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(486, NULL); -- Raccoon
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(487, NULL); -- Flying squirrel
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(488, NULL); -- Giant Black squirrel
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(489, NULL); -- Woodchuck
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(542, NULL); -- Owlbear
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(586, NULL); -- Selkie
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(587, NULL); -- Shadow
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(609, NULL); -- Spectre
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(630, NULL); -- Su-Monster
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(659, NULL); -- Spirit Troll
-- INSERT INTO MONSTER_ACTIVITY_CYCLE ([MONSTER_ID], [ACTIVITY_CYCLE_ID]) VALUES(688, NULL); -- Wyvern

COMMIT TRANSACTION;