BEGIN TRANSACTION;

INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (1, 513); -- Aarakocra
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (2, 260); -- Aboleth
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (3, 514); -- Ankheg
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (4, 258); -- Arcane
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (5, 516); -- Argos
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (6, 514); -- Aurumvorax
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (7, 260); -- Baatezu, Pit fiend
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (8, 260); -- Baatezu, Black Abishai
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (9, 260); -- Baatezu, Green Abishai
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (10, 260); -- Baatezu, Red Abishai
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (11, 1028); -- Banshee
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (12, 514); -- Basilisk, Lesser
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (13, 514); -- Basilisk, Greater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (14, 1028); -- Basilisk, Dracolisk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (15, 514); -- Bat, Common
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (16, 514); -- Bat, Large
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (17, 516); -- Bat, Huge
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (18, 1026); -- Bat, Azmyth
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (19, 516); -- Bat, Night hunter
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (20, 260); -- Bat, Sinister
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (21, 514); -- Bear, Black
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (22, 514); -- Bear, Brown
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (23, 514); -- Bear, Cave
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (24, 514); -- Bear, Polar
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (25, 514); -- Beetle, Giant, Bombardier
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (26, 514); -- Beetle, Giant, Boring
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (27, 514); -- Beetle, Giant, Fire
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (28, 514); -- Beetle, Giant, Rhinoceros
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (29, 514); -- Beetle, Giant, Stag
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (30, 514); -- Beetle, Giant, Water
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (31, 516); -- Behir
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (32, 260); -- Beholder
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (33, 516); -- Beholder, Death kiss
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (34, 260); -- Beholder, Eye of the deep
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (35, 516); -- Beholder, Gauth
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (36, 258); -- Beholder, Spectator
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (37, 260); -- Beholder, Undead
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (38, 260); -- Beholder, Hive mother
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (39, 260); -- Beholder, Director
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (40, 258); -- Beholder, Examiner
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (41, 516); -- Beholder, Lensman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (42, 260); -- Beholder, Overseer
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (43, 514); -- Beholder, Watcher
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (44, 260); -- Beholder, Mage
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (45, 260); -- Beholder, Elder orb
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (46, 514); -- Beholder, Orbus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (47, 260); -- Beholder, Doomsphere
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (48, 516); -- Beholder, Kasharin
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (49, 260); -- Beholder, Astereater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (50, 514); -- Beholder, Gorbel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (51, NULL); -- Bird, Blood hawk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (52, 514); -- Bird, Boobrie
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (53, NULL); -- Bird, Condor
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (54, 514); -- Bird, Giant eagle
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (55, 514); -- Bird, Wild eagle
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (56, 516); -- Bird, Eblis
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (57, 514); -- Bird, Emre
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (58, NULL); -- Bird, Falcon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (59, 514); -- Bird, Flightless bird
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (60, NULL); -- Bird, Large hawk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (61, 514); -- Bird, Kingfisher
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (62, 514); -- Bird, Owl
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (63, 514); -- Bird, Giant owl
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (64, 257); -- Bird, Talking owl
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (65, 514); -- Bird, Raven
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (66, NULL); -- Bird, Huge raven
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (67, NULL); -- Bird, Giant raven
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (68, 514); -- Bird, Skyfisher
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (69, 514); -- Bird, Swan
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (70, NULL); -- Bird, Vulture
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (71, NULL); -- Bird, Giant vulture
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (72, 514); -- Brain mole
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (73, 516); -- Broken one, Common
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (74, 516); -- Broken one, Greater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (75, 257); -- Brownie
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (76, NULL); -- Brownie, Killmoulis
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (77, 1028); -- Bugbear
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (78, 514); -- Bulette
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (79, 1028); -- Bullywug
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (80, 514); -- Carrion crawler
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (81, 514); -- Cat, Great, Cheetah
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (82, 514); -- Cat, Great, Jaguar
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (83, 514); -- Cat, Great, Leopard
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (84, 514); -- Cat, Great, Common lion
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (85, 514); -- Cat, Great, Mountain lion
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (86, 514); -- Cat, Great, Spotted lion
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (87, 514); -- Cat, Great, Giant lynx
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (88, 514); -- Cat, Great, Wild tiger
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (89, 514); -- Cat, Great, Smilodon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (90, 514); -- Cat, Small, Domestic
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (91, 514); -- Cat, Small, Wild
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (92, 514); -- Cat, Small, Elven
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (93, 514); -- Catoblepas
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (94, 514); -- Cave fisher
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (95, 513); -- Centaur
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (95, 1025); -- Centaur
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (96, 514); -- Centipede, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (97, 514); -- Centipede, Huge
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (98, 514); -- Centipede, Megalo
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (99, 514); -- Centipede, Tunnel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (100, 1028); -- Chimera
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (101, 514); -- Chimera, Gorgimera
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (102, 1026); -- Cloaker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (103, 514); -- Cockatrice
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (104, 516); -- Cockatrice, Pyrolisk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (105, 257); -- Couatl
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (106, 514); -- Crabman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (107, 514); -- Crawling Claw
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (108, 514); -- Crocodile
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (109, 514); -- Crocodile, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (110, 514); -- Crustacean, Giant crab
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (111, 514); -- Crustacean, Giant crayfish
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (112, 514); -- Crypt Thing
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (113, 1028); -- Death Knight
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (114, 1028); -- Deepspawn
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (115, 514); -- Dinosaur, Ankylosaurus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (116, 514); -- Dinosaur, Deinonychus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (117, 514); -- Dinosaur, Diplodocus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (118, 514); -- Dinosaur, Elasmosaurus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (119, 514); -- Dinosaur, Lambeosaurus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (120, 514); -- Dinosaur, Pteranodon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (121, 514); -- Dinosaur, Stegosaurus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (122, 514); -- Dinosaur, Triceratops
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (123, 514); -- Dinosaur, Tyrannosaurus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (124, 260); -- Displacer Beast
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (125, 514); -- Dog, Wild dog
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (126, 514); -- Dog, War dog
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (127, 257); -- Dog, Blink dog
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (128, 516); -- Dog, Death dog
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (129, 513); -- Dog, Moon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (130, 257); -- Dolphin
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (131, 514); -- Doppleganger
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (132, 260); -- Dracolich
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (132, 1028); -- Dracolich
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (132, 1028); -- Dracolich
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (133, 1028); -- Dragon, Chromatic, Black
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (134, 260); -- Dragon, Chromatic, Blue
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (135, 260); -- Dragon, Chromatic, Green
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (136, 1028); -- Dragon, Chromatic, Red
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (137, 1028); -- Dragon, Chromatic, White
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (138, 514); -- Dragon, Gem, Amethyst
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (139, 1026); -- Dragon, Gem, Crystal
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (140, 258); -- Dragon, Gem, Emerald
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (141, 258); -- Dragon, Gem, Sapphire
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (142, 1026); -- Dragon, Gem, Topaz
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (143, 1025); -- Dragon, Metallic, Brass
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (143, 1026); -- Dragon, Metallic, Brass
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (144, 257); -- Dragon, Metallic, Bronze
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (145, 1025); -- Dragon, Metallic, Copper
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (146, 257); -- Dragon, Metallic, Gold
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (147, 257); -- Dragon, Metallic, Silver
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (148, 514); -- Brown Dragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (148, 516); -- Brown Dragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (149, 514); -- Cloud Dragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (150, 1028); -- Deep Dragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (151, 1025); -- Mercury Dragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (152, 514); -- Mist Dragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (153, 1028); -- Shadow Dragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (154, 257); -- Steel Dragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (154, 258); -- Steel Dragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (155, 1028); -- Yellow Dragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (156, 514); -- Dragon turtle
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (157, 1025); -- Dragonet, Faerie dragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (158, 514); -- Dragonet, Firedrake
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (159, 513); -- Dragonet, Pseudodragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (159, 514); -- Dragonet, Pseudodragon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (160, 514); -- Dragonne
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (161, 514); -- Dryad
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (162, 257); -- Dwarf, Hill
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (163, 257); -- Dwarf, Mountain
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (164, 1028); -- Dwarf, Derro
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (165, 260); -- Dwarf, Duergar
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (165, 514); -- Dwarf, Duergar
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (166, 514); -- Elemental, Air
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (167, 514); -- Elemental, Earth
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (168, 514); -- Elemental, Fire
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (169, 514); -- Elemental, Water
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (170, 513); -- Elemental, Air Kin, Sylph
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (170, 514); -- Elemental, Air Kin, Sylph
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (171, 514); -- Elemental, Air Kin, Aerial servant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (172, 513); -- Elemental, Earth Kin, Pech
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (173, 514); -- Elemental, Earth Kin, Sandling
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (174, 1028); -- Elemental, Fire Kin, Salamander
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (175, 514); -- Elemental, Fire Kin, Fire snake
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (176, 1025); -- Elemental, Water Kin, Nereid
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (176, 1026); -- Elemental, Water Kin, Nereid
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (176, 1028); -- Elemental, Water Kin, Nereid
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (177, 1028); -- Elemental, Water Kin, Water weird
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (178, 1026); -- Elemental, Composite, Tempest
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (179, 516); -- Elemental, Composite, Skriaxit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (180, 514); -- Elephant, African
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (181, 514); -- Elephant, Mammoth
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (182, 514); -- Elephant, Mastodon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (183, 514); -- Elephant, Oliphant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (184, 1025); -- Elf
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (185, 1025); -- Elf, Aquatic
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (186, 1028); -- Elf, Drow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (187, 1028); -- Elf, Drider
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (188, 516); -- Ettercap
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (189, 260); -- Eyewing
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (190, 1028); -- Feyr
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (191, 1028); -- Great Feyr
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (192, 514); -- Fish, Barracuda
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (193, 514); -- Fish, Giant carp
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (194, NULL); -- Fish, Giant catfish
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (195, NULL); -- Fish, Dragonfish
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (196, 514); -- Fish, Electric eel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (197, 514); -- Fish, Giant eel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (198, 514); -- Fish, Marine eel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (199, 514); -- Fish, Weed eel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (200, NULL); -- Fish, Giant gar
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (201, 514); -- Fish, Lamprey
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (202, 514); -- Fish, Giant lamprey
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (203, 514); -- Fish, Land lamprey
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (204, 514); -- Fish, Manta ray
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (205, NULL); -- Fish, Giant pike
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (206, NULL); -- Fish, Piranha
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (207, NULL); -- Fish, Giant piranha
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (208, 514); -- Fish, Pungi ray
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (209, NULL); -- Fish, Quipper
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (210, 514); -- Fish, Giant sea horse
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (211, 514); -- Fish, Shark
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (212, 514); -- Fish, Giant shark
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (213, 514); -- Fish, Sting ray
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (214, NULL); -- Frog, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (215, NULL); -- Frog, Killer
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (216, NULL); -- Frog, Poisonous
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (217, 514); -- Fungus, Violet
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (218, 514); -- Fungus, Shrieker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (219, 514); -- Fungus, Phycomid
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (219, 516); -- Fungus, Phycomid
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (220, 514); -- Fungus, Ascomoid
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (220, 516); -- Fungus, Ascomoid
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (221, 514); -- Fungus, Gas spore
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (222, 514); -- Galeb Duhr
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (223, 1026); -- Gargantua Reptilian
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (224, 1026); -- Gargantua Humanoid
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (225, 1026); -- Gargantua Insectoid
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (226, 1028); -- Gargoyle
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (227, 1028); -- Gargoyle, Margoyle
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (228, 1025); -- Genie, Djinni
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (229, 516); -- Genie, Dao
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (230, 260); -- Genie, Efreeti
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (230, 514); -- Genie, Efreeti
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (231, 1026); -- Genie, Marid
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (232, 513); -- Genie, Jann
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (232, 514); -- Genie, Jann
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (233, 260); -- Ghost
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (234, 1028); -- Ghoul
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (235, 1028); -- Ghoul, Lacedon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (236, 1028); -- Ghoul, Ghast
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (237, 513); -- Giant, Cloud
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (237, 516); -- Giant, Cloud
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (238, 1028); -- Giant, Cyclopskin
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (239, 1028); -- Giant, Cyclops
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (240, 514); -- Giant, Desert
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (241, 1028); -- Giant, Ettin
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (242, 514); -- Giant, Firbolg
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (242, 1025); -- Giant, Firbolg
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (243, 260); -- Giant, Fire
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (244, 513); -- Giant, Fog
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (244, 516); -- Giant, Fog
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (245, 516); -- Giant, Formorian
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (246, 1028); -- Giant, Frost
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (247, 1028); -- Giant, Hill
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (248, 514); -- Giant, Jungle
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (249, 1026); -- Giant, Mountain
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (250, 513); -- Giant, Reef
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (251, 514); -- Giant, Stone
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (252, 1025); -- Giant, Storm
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (253, 514); -- Giant, Verbeeg
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (253, 516); -- Giant, Verbeeg
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (254, 1025); -- Giant, Wood
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (255, 1026); -- Gibberling
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (256, 258); -- Giff
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (257, 1028); -- Gith
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (258, 260); -- Gith, Pirate
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (259, 260); -- Githyanki
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (259, 516); -- Githyanki
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (259, 1028); -- Githyanki
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (260, 1026); -- Githzerai
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (261, 514); -- Gloomwing, Moth
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (262, 514); -- Gloomwing, Tenebrous worm
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (263, 1028); -- Gnoll
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (264, 260); -- Gnoll, Flind
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (265, 513); -- Gnome, Rock
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (266, 513); -- Gnome, Svirfneblin
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (266, 514); -- Gnome, Svirfneblin
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (267, 257); -- Gnome, Tinker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (267, 514); -- Gnome, Tinker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (268, 513); -- Gnome, Forest
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (269, 1028); -- Gnome, Spriggan
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (270, 260); -- Goblin
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (271, 514); -- Golem, Greater, Stone
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (272, 514); -- Golem, Greater, Iron
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (273, 514); -- Golem, Lesser, Flesh
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (274, 514); -- Golem, Lesser, Clay
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (275, 514); -- Golem, Bone
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (276, 514); -- Golem, Doll
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (277, 514); -- Golem, Gargoyle
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (278, 514); -- Golem, Glass
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (279, 514); -- Golem, Necrophidus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (280, 514); -- Golem, Scarecrow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (281, 514); -- Golem, Stone Variants, Caryatid column
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (282, 514); -- Golem, Stone Variants, Juggernaut
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (283, 514); -- Golem, Stone Variants, Stone guardian
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (284, 514); -- Gorgon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (285, 516); -- Grell Worker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (286, 516); -- Grell Philosopher
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (287, 516); -- Grell Patriarch
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (288, 1028); -- Gremlin
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (289, 1026); -- Gremlin, Fremlin
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (290, 1028); -- Gremlin, Galltrit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (291, 260); -- Gremlin, Mite
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (292, 514); -- Gremlin, Snyad
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (293, 260); -- Gremlin, Jermlaine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (293, 516); -- Gremlin, Jermlaine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (294, 514); -- Griffon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (295, 516); -- Grimlock
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (296, 514); -- Grippli
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (297, 1028); -- Hag, Annis
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (298, 516); -- Hag, Green
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (299, 1028); -- Hag, Sea
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (300, 257); -- Halfling, Hairfoot
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (301, 257); -- Halfling, Tallfellow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (302, 257); -- Halfling, Stout
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (303, 1028); -- Harpy
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (304, 1026); -- Hatori, Lesser
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (305, 1026); -- Hatori, Greater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (306, 257); -- Haunt
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (306, 258); -- Haunt
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (306, 260); -- Haunt
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (306, 513); -- Haunt
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (306, 514); -- Haunt
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (306, 516); -- Haunt
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (306, 1025); -- Haunt
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (306, 1026); -- Haunt
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (306, 1028); -- Haunt
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (307, 260); -- Hell Hound
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (308, 1028); -- Heucuva
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (309, 1025); -- Hippocampus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (310, 514); -- Hippogriff
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (311, 260); -- Hobgoblin
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (312, 257); -- Homonculus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (312, 258); -- Homonculus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (312, 260); -- Homonculus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (312, 513); -- Homonculus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (312, 514); -- Homonculus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (312, 516); -- Homonculus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (312, 1025); -- Homonculus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (312, 1026); -- Homonculus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (312, 1028); -- Homonculus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (313, 514); -- Hook Horror
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (314, 514); -- Horse, Draft
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (315, 514); -- Horse, Heavy
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (316, 514); -- Horse, Medium
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (317, 514); -- Horse, Light
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (318, 514); -- Horse, Pony
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (319, 514); -- Horse, Wild
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (320, 514); -- Horse, Riding
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (321, 514); -- Horse, Mule
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (322, NULL); -- Human, Aborigine/Caveman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (323, NULL); -- Human, Adventurer
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (324, NULL); -- Human, Bandit/Brigand
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (325, NULL); -- Human, Barbarian/Nomad
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (326, NULL); -- Human, Berserker/Dervish
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (327, NULL); -- Human, Farmer/Herder
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (328, NULL); -- Human, Gentry
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (329, NULL); -- Human, Knight
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (330, NULL); -- Human, Mercenary
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (331, NULL); -- Human, Merchant Sailor/Fisherman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (332, NULL); -- Human, Merchant/Trader
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (333, NULL); -- Human, Middle class
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (334, NULL); -- Human, Peasant/Serf
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (335, NULL); -- Human, Pilgrim
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (336, NULL); -- Human, Pirate/Buccaneer
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (337, NULL); -- Human, Police/Constabulary
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (338, NULL); -- Human, Priest
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (339, NULL); -- Human, Sailor
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (340, NULL); -- Human, Slaver
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (341, NULL); -- Human, Soldier
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (342, NULL); -- Human, Thief/Thug
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (343, NULL); -- Human, Tradesman/Craftsman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (344, NULL); -- Human, Tribesman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (345, NULL); -- Human, Wizard
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (346, 514); -- Hydra
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (347, 514); -- Hydra, Lernaean
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (348, 514); -- Hydra, Pyrohydra
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (349, 514); -- Hydra, Cryohydra
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (350, 260); -- Imp
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (351, 1028); -- Imp, Quasit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (352, 1025); -- Imp, Mephit, Fire Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (352, 1026); -- Imp, Mephit, Fire Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (352, 1028); -- Imp, Mephit, Fire Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (353, 1025); -- Imp, Mephit, Ice Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (353, 1026); -- Imp, Mephit, Ice Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (353, 1028); -- Imp, Mephit, Ice Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (354, 1025); -- Imp, Mephit, Lava Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (354, 1026); -- Imp, Mephit, Lava Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (354, 1028); -- Imp, Mephit, Lava Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (355, 1025); -- Imp, Mephit, Mist Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (355, 1026); -- Imp, Mephit, Mist Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (355, 1028); -- Imp, Mephit, Mist Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (356, 1025); -- Imp, Mephit, Smoke Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (356, 1026); -- Imp, Mephit, Smoke Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (356, 1028); -- Imp, Mephit, Smoke Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (357, 1025); -- Imp, Mephit, Steam Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (357, 1026); -- Imp, Mephit, Steam Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (357, 1028); -- Imp, Mephit, Steam Mephit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (358, NULL); -- Insect, Ant, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (359, NULL); -- Insect, Ant Lion, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (360, 514); -- Insect, Aratha
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (361, 514); -- Insect, Aspis, cow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (362, 514); -- Insect, Aspis, drone
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (363, 514); -- Insect, Aspis, larva
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (364, NULL); -- Insect, Assassin Bug
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (365, NULL); -- Insect, Bee, Worker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (366, NULL); -- Insect, Bee, Soldier
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (367, NULL); -- Insect, Bumblebee
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (368, NULL); -- Insect, Cave cricket
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (369, 514); -- Insect, Dragonfly, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (370, 514); -- Insect, Dragonfly, Larva
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (371, NULL); -- Insect, Ear seeker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (372, NULL); -- Insect, Firefriend
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (373, NULL); -- Insect, Fly, Bluebottle
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (374, NULL); -- Insect, Fly, Horsefly
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (375, NULL); -- Insect, Fyrefly
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (376, NULL); -- Insect, Horax
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (377, NULL); -- Insect, Hornet, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (378, NULL); -- Insect, Pernicon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (379, NULL); -- Insect, Praying Mantis
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (380, 514); -- Insect, Termite, Giant harvester, King
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (381, 514); -- Insect, Termite, Giant harvester, Queen
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (382, 514); -- Insect, Termite, Giant harvester, Soldier
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (383, 514); -- Insect, Termite, Giant harvester, Worker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (384, NULL); -- Insect, Tick, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (385, NULL); -- Insect, Wasp, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (386, 514); -- Insect Swarm, Velvet ants swarm
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (387, 514); -- Insect Swarm, Grasshoppers swarm
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (388, 514); -- Insect Swarm, Locust swarm
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (389, 1028); -- Intellect devourer, adult
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (390, 514); -- Intellect devourer, larva
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (390, 516); -- Intellect devourer, larva
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (391, 514); -- Invisible Stalker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (392, 1028); -- Ixitxachitl
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (393, 1028); -- Jackalwere
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (394, 514); -- Kenku
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (395, 257); -- Ki-rin
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (396, 514); -- Kirre
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (397, 260); -- Kobold
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (398, 516); -- Kobold, Urd
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (399, 516); -- Kuo-toa
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (399, 1028); -- Kuo-toa
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (400, 1028); -- Lamia
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (401, 1028); -- Lamia, Noble
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (402, 257); -- Lammasu, Lesser
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (403, 257); -- Lammasu, Greater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (404, 514); -- Leech, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (405, 514); -- Leech, Throat
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (406, 514); -- Leech, Swarm
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (407, 514); -- Leprechaun
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (408, 1028); -- Leucrotta
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (409, 260); -- Lich
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (409, 516); -- Lich
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (409, 1028); -- Lich
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (410, 260); -- Lich, Demilich
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (410, 516); -- Lich, Demilich
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (410, 1028); -- Lich, Demilich
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (411, 1028); -- Living Wall
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (412, 514); -- Lizard, Fire
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (413, 514); -- Lizard, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (414, 514); -- Lizard, Minotaur
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (415, 514); -- Lizard, Subterranean
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (416, 514); -- Lizard Man
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (417, 1028); -- Lizard Man, King
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (418, 514); -- Locathah
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (419, 514); -- Lurker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (420, 514); -- Lurker, Trapper
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (421, 514); -- Lurker, Trapper, Forest
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (422, 516); -- Lycanthrope, Seawolf, Lesser
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (423, 1028); -- Lycanthrope, Seawolf, Greater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (424, 516); -- Lycanthrope, Werebat
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (425, 1025); -- Lycanthrope, Werebear
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (426, 514); -- Lycanthrope, Wereboar
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (427, 1028); -- Lycanthrope, Werefox
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (428, 260); -- Lycanthrope, Wererat
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (429, 513); -- Lycanthrope, Wereraven
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (430, 514); -- Lycanthrope, Weretiger
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (431, 1028); -- Lycanthrope, Werewolf
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (432, 514); -- Mammal, Ape, Carnivorous
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (433, 514); -- Mammal, Baboon, Wild
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (434, 514); -- Mammal, Badger
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (435, 514); -- Mammal, Banderlog
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (436, 514); -- Mammal, Bhaergala
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (437, 514); -- Mammal, Boar, Wild
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (438, 1025); -- Mammal, Chattur
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (439, NULL); -- Mammal, Cooshee
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (440, NULL); -- Mammal, Dakon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (441, NULL); -- Mammal, Debbi
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (442, NULL); -- Mammal, Goat
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (443, NULL); -- Mammal, Gorilla
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (444, 514); -- Mammal, Hsing-sing
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (445, NULL); -- Mammal, Hyena
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (446, 514); -- Mammal, Jackal
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (447, NULL); -- Mammal, Losel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (448, 513); -- Mammal, Monkey Spider
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (449, NULL); -- Mammal, Osquip
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (450, NULL); -- Mammal, Porcupine, Black
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (451, NULL); -- Mammal, Porcupine, Brown
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (452, NULL); -- Mammal, Rothe
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (453, 514); -- Mammal, Skunk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (454, 1026); -- Mammal, Sleek
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (455, NULL); -- Mammal, Stag, Wild
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (456, NULL); -- Mammal, Stench Kow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (457, 514); -- Mammal, Taer
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (458, 1026); -- Mammal, Tyrg
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (459, 514); -- Mammal, Warthog
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (460, 514); -- Mammal, Weasel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (461, NULL); -- Mammal, Wolverine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (462, NULL); -- Mammal, Herd, Camel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (463, 514); -- Mammal, Herd, Cattle
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (464, NULL); -- Mammal, Herd, Buffalo
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (465, NULL); -- Mammal, Herd, Antelope
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (466, NULL); -- Mammal, Herd, Sheep
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (467, NULL); -- Mammal, Small, Beaver
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (468, NULL); -- Mammal, Small, Chipmunk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (469, NULL); -- Mammal, Small, Ermine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (470, NULL); -- Mammal, Small, Ferret
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (471, NULL); -- Mammal, Small, Fox
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (472, NULL); -- Mammal, Small, Gopher
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (473, NULL); -- Mammal, Small, Hedgehog
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (474, NULL); -- Mammal, Small, Mink
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (475, NULL); -- Mammal, Small, Mole
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (476, NULL); -- Mammal, Small, Monkey
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (477, NULL); -- Mammal, Small, Mouse
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (478, NULL); -- Mammal, Small, Muskrat
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (479, NULL); -- Mammal, Small, Opossum
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (480, NULL); -- Mammal, Small, Otter
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (481, NULL); -- Mammal, Small, Otter, Sea
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (482, NULL); -- Mammal, Small, Otter, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (483, NULL); -- Mammal, Small, Pig, Domestic
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (484, NULL); -- Mammal, Small, Pig, Wild
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (485, NULL); -- Mammal, Small, Rabbit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (486, NULL); -- Mammal, Small, Raccoon
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (487, NULL); -- Mammal, Small, Squirrel Flying
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (488, NULL); -- Mammal, Small, Squirrel, Giant Black
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (489, NULL); -- Mammal, Small, Woodchuck
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (490, 516); -- Manscorpion
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (491, 260); -- Manticore
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (492, 260); -- Medusa
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (493, 260); -- Medusa, Greater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (494, 260); -- Maedar
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (495, 260); -- Maedar, Glyptar
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (496, 514); -- Merman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (497, 514); -- Mimic
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (498, 514); -- Mimic, Killer Mimic
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (498, 516); -- Mimic, Killer Mimic
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (499, 260); -- Mind Flayer
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (500, 1028); -- Minotaur
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (501, 516); -- Mist, Crimson Death
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (502, 516); -- Mist, Vampiric
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (503, 514); -- Mold, Brown Mold
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (504, 514); -- Mold, Russet Mold
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (505, 514); -- Mold, Yellow Mold
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (506, 514); -- Mold Man
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (507, 258); -- Mongrelman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (508, 1028); -- Morkoth
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (509, 260); -- Muckdweller
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (510, 514); -- Mudman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (511, 260); -- Mummy
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (512, 260); -- Mummy Greater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (513, 258); -- Myconid
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (514, 257); -- Naga, Guardian
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (515, 1028); -- Naga, Spirit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (516, 514); -- Naga, Water
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (517, 260); -- Naga, Dark
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (518, 260); -- Neogi
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (519, 260); -- Neogi, Great Old Master
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (520, 516); -- Nightmare
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (521, 513); -- Nymph
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (521, 514); -- Nymph
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (522, 514); -- Octopus giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (522, 516); -- Octopus giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (523, 1028); -- Ogre
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (524, 260); -- Ogre, Mage
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (525, 1028); -- Ogre, Merrow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (526, 1028); -- Ogre, Half-Ogre
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (527, 1028); -- Ogre, Ogrillion
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (528, 514); -- Ooze, Slime, Jelly, Olive Slime
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (529, 514); -- Ooze, Slime, Jelly, Olive Slime Creature
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (530, 514); -- Ooze, Slime, Jelly, Mustard Jelly
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (531, 514); -- Ooze, Slime, Jelly, Stunjelly
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (532, 514); -- Ooze, Slime, Jelly, Ochre Jelly
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (533, 514); -- Ooze, Slime, Jelly, Gray Ooze
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (534, 514); -- Ooze, Slime, Jelly, Crystal Ooze
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (535, 514); -- Ooze, Slime, Jelly, Gelatinous Cube
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (536, 514); -- Ooze, Slime, Jelly, Green Slime
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (537, 514); -- Ooze, Slime, Jelly, Slithering Tracker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (538, 260); -- Orc
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (539, 260); -- Orc, Orog
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (540, 514); -- Otyugh
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (541, 514); -- Otyugh, Neo-Otyugh
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (542, 514); -- Owlbear
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (543, 1025); -- Pegasus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (544, 1028); -- Peryton
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (545, 514); -- Phantom
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (546, 513); -- Phoenix
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (547, 514); -- Piercer
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (548, 514); -- Plant, Dangerous, Choke Ceeper
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (549, 514); -- Plant, Dangerous, Mantrap
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (550, 514); -- Plant, Dangerous, Retch Plant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (551, 514); -- Plant, Dangerous, Snapper Saw
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (552, 514); -- Plant, Dangerous, Thornslinger
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (553, 514); -- Plant, Dangerous, Tri-Flower Frond
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (554, 514); -- Plant, Dangerous, Yellow Musk Creeper
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (555, 514); -- Plant, Dangerous, Yellow Musk Zombie
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (556, 514); -- Plant, Intelligent, Hangman tree
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (556, 516); -- Plant, Intelligent, Hangman tree
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (557, 516); -- Plant, Intelligent, Kelpie
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (558, 516); -- Plant, Intelligent, Obliviax
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (559, 514); -- Plant, Intelligent, Quickwood
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (560, 514); -- Plant, Intelligent, Shambling mound
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (561, 514); -- Plant, Intelligent, Strangleweed
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (562, 514); -- Plant, Intelligent, Giant Sundew
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (563, 514); -- Plant, Intelligent, Thorny
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (564, 260); -- Poltergeist
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (565, 514); -- Pudding, Deadly, Black
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (566, 514); -- Pudding, Deadly, White
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (567, 514); -- Pudding, Deadly, Brown
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (568, 514); -- Pudding, Deadly, Dun
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (569, 514); -- Quaggoth
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (570, 260); -- Rakshasa
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (571, 260); -- Rakshasa, Greater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (572, 516); -- Rat, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (573, 514); -- Rat, Osquip
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (574, 514); -- Remorhaz
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (575, 514); -- Revenant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (576, 514); -- Roc
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (577, 1028); -- Roper
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (578, 514); -- Rust Monster
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (579, 260); -- Sahuagin
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (580, 514); -- Satyr
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (581, 1026); -- Satyr, Korred
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (582, 514); -- Scorpion, Large
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (583, 514); -- Scorpion, Huge
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (584, 514); -- Scorpion, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (585, 514); -- Sea Lion
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (586, 513); -- Selkie
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (586, 514); -- Selkie
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (587, 1028); -- Shadow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (588, 257); -- Shedu, Lesser
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (589, 257); -- Shedu, Greater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (590, 257); -- Sirine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (590, 258); -- Sirine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (590, 260); -- Sirine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (590, 513); -- Sirine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (590, 514); -- Sirine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (590, 516); -- Sirine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (590, 1025); -- Sirine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (590, 1026); -- Sirine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (590, 1028); -- Sirine
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (591, 514); -- Skeleton
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (592, 514); -- Skeleton, Animal
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (593, 514); -- Skeleton, Monster
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (594, 514); -- Skeleton, Giant Skeleton
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (595, 516); -- Skeleton, Warrior
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (596, 1026); -- Slaad, Red
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (597, 1026); -- Slaad, Blue
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (598, 514); -- Slug, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (599, 514); -- Snake, Amphisbaena
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (600, 514); -- Snake, Boalisk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (601, 514); -- Snake, Constrictor
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (602, 514); -- Snake, Giant constrictor
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (603, 1028); -- Snake, Heway
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (604, 514); -- Snake, Poisonous
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (605, 514); -- Snake, Giant poisonous
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (606, 514); -- Snake, Giant sea
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (607, 514); -- Snake, Spitting
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (608, 514); -- Snake, Winged
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (609, 260); -- Spectre
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (610, 1025); -- Sphinx, Androsphinx
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (611, 514); -- Sphinx, Criosphinx
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (612, 514); -- Sphinx, Gynosphinx
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (613, 1028); -- Sphinx, Hieracosphinx
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (614, 516); -- Spider, Hairy
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (615, 514); -- Spider, Large
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (616, 514); -- Spider, Huge
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (617, 1028); -- Spider, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (618, 514); -- Spider, Phase
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (619, 1028); -- Spider, Sword
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (620, 1028); -- Spider, Gargantuan
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (621, 513); -- Sprite
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (621, 514); -- Sprite
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (622, 1026); -- Sprite, Sea sprite
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (623, 514); -- Sprite, Pixie
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (624, 514); -- Sprite, Nixie
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (625, 1026); -- Sprite, Atomie
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (626, 513); -- Sprite, Grig
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (626, 514); -- Sprite, Grig
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (627, 514); -- Squid, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (628, 516); -- Squid, Kraken
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (629, NULL); -- Stirge
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (630, 1028); -- Su-Monster
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (631, 257); -- Swanmay
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (631, 513); -- Swanmay
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (631, 1025); -- Swanmay
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (632, 257); -- Swanmay, Bird maiden
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (632, 258); -- Swanmay, Bird maiden
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (632, 260); -- Swanmay, Bird maiden
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (632, 513); -- Swanmay, Bird maiden
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (632, 514); -- Swanmay, Bird maiden
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (632, 516); -- Swanmay, Bird maiden
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (632, 1025); -- Swanmay, Bird maiden
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (632, 1026); -- Swanmay, Bird maiden
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (632, 1028); -- Swanmay, Bird maiden
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (633, 1026); -- Tabaxi
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (634, 1028); -- Tabaxi Lord
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (635, 258); -- Tako, Male
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (636, 258); -- Tako, Female
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (637, 1028); -- Tanar'ri, Balor
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (638, 1028); -- Tanar'ri, Marilith
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (639, 514); -- Tarrasque
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (640, 1028); -- Tasloi
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (641, 514); -- Thought-Eater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (642, 1026); -- Thri-Kreen
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (643, 1025); -- Titan
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (644, 514); -- Toad, Giant, Giant Toad
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (645, 1026); -- Toad, Giant, Fire Toad
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (646, 514); -- Toad, Giant, Ice Toad
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (647, 514); -- Toad, Giant, Poisonous Toad
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (648, 1025); -- Treant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (649, 513); -- Triton
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (649, 514); -- Triton
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (650, 1028); -- Troglodyte
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (651, 1028); -- Troll
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (652, 1028); -- Troll, Two-headed
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (653, 1028); -- Troll, Freshwater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (654, 1028); -- Troll, Saltwater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (655, 1028); -- Troll, Desert
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (656, 1028); -- Troll, Spectral
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (657, 1028); -- Troll, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (658, 1028); -- Troll, Ice
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (659, 1028); -- Troll, Spirit
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (660, 1028); -- Umber Hulk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (661, 1028); -- Umber Hulk, Vodyanoi
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (662, 1025); -- Unicorn
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (663, 514); -- Urchin, Black
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (664, 514); -- Urchin, Green
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (665, 514); -- Urchin, Red
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (666, 514); -- Urchin, Silver
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (667, 514); -- Urchin, Yellow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (668, 514); -- Urchin, Land
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (669, 1028); -- Vampire
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (670, 514); -- Wemic
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (671, 514); -- Whale, Common
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (672, 514); -- Whale, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (673, 514); -- Whale, Leviathan
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (674, 514); -- Whale, Killer
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (675, 514); -- Whale, Narwhal
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (676, 260); -- Wight
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (677, 1028); -- Will o'wisp
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (678, 514); -- Wolf
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (679, 516); -- Wolf, Worg
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (680, 514); -- Wolf, Dire
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (681, 516); -- Wolf, Winter
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (682, 1028); -- Wolfwere
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (683, 514); -- Worm, Purple
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (684, 514); -- Worm, Giant Bloodworm
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (685, 514); -- Worm, Bookworm
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (686, 514); -- Worm, Rot Grub
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (687, 260); -- Wraith
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (688, 514); -- Wyvern
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (688, 516); -- Wyvern
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (689, 514); -- Xorn
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (690, 514); -- Xorn, Xaren
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (691, 514); -- Yeti
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (692, 1028); -- Yuan-ti
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (693, 1028); -- Yuan-ti, Histachii
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (694, 514); -- Yugoloth, Guardian, Least
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (695, 514); -- Yugoloth, Guardian, Lesser
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (695, 516); -- Yugoloth, Guardian, Lesser
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (696, 514); -- Yugoloth, Guardian, Greater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (696, 516); -- Yugoloth, Guardian, Greater
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (697, 514); -- Zaratan
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (698, 514); -- Zombie
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (699, 514); -- Zombie, Monster
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (700, 516); -- Zombie, Ju-ju
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (701, 516); -- Zombie, Lord
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (702, 1028); -- Zombie, Sea
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (707, 514); -- Rat
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (708, 1026); -- Death Slaad
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (709, 1026); -- Gray Slaad
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (710, 1026); -- Green Slaad
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (711, 514); -- Aspis, Cow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (712, 514); -- Aspis, Drone
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (713, 514); -- Aspis, Larva
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (714, 513); -- Beastman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (714, 514); -- Beastman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (715, 514); -- Beetle, Death Watch
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (716, 514); -- Beetle, Slicer
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (717, 514); -- Beetle, Stink
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (718, 514); -- Bonesnapper
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (719, 514); -- Booka
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (719, 1025); -- Booka
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (720, 514); -- Brownie, Buckawn
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (721, 1026); -- Brownie, Quickling
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (721, 1028); -- Brownie, Quickling
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (722, 514); -- Crystalmist
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (723, 257); -- Dragon (Oerth), Greyhawk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (723, 258); -- Dragon (Oerth), Greyhawk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (724, 514); -- Dragonfly, Giant, Adult
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (725, 514); -- Dragonfly, Giant, Larva (Nymph)
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (726, 514); -- Dragonnel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (726, 516); -- Dragonnel
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (727, 1026); -- Elf, Grugach
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (728, 1026); -- Elf, Valley
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (729, 514); -- Golem, Necrophidius
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (730, 516); -- Grell, Wild
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (731, 260); -- Grung
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (732, 1028); -- Hobgoblin, Norker
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (733, 514); -- Horgar
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (734, 516); -- Hound, Yeth
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (735, 514); -- Iguana, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (736, 1028); -- Ingundi
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (737, 516); -- Kech
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (738, 1028); -- Kyuss, Son of
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (739, 260); -- Mite
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (740, 514); -- Mite, Snyad (Pestie)
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (741, 514); -- Needleman
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (742, 514); -- Plant, Carnivorous (Oerth), Kampfult
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (743, 516); -- Plant, Carnivorous (Oerth), Polyp, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (744, 514); -- Plant, Carnivorous, Vampire Cactus
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (745, 514); -- Rat (Oerth), Camprat
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (746, 1026); -- Rat (Oerth), Vapor Rat
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (747, 514); -- Raven/Crow, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (747, 516); -- Raven/Crow, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (748, 514); -- Raven/Crow, Huge
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (748, 516); -- Raven/Crow, Huge
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (749, 514); -- Raven/Crow, Ordinary
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (750, 260); -- Scarecrow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (750, 516); -- Scarecrow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (750, 1028); -- Scarecrow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (751, 1028); -- Shadow, Slow
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (752, 1028); -- Skulk
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (753, 514); -- Snail, Flail
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (754, 514); -- Snail, Sea
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (755, 514); -- Taer
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (756, 514); -- Tentamort
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (757, 514); -- Turtle, Giant, Sea, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (758, 514); -- Turtle, Giant, Snapping, Giant
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (759, 1026); -- Tyrg
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (760, 257); -- Wolf, Mist
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (761, 516); -- Wraith (Oerth), Soul Beckoner
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (762, 260); -- Wraith (Oerth), Swordwraith
INSERT INTO MONSTER_ALIGNMENT ([MONSTER_ID], [ALIGNMENT_ID]) VALUES (763, 516); -- Zygom

COMMIT TRANSACTION;