BEGIN TRANSACTION;

INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (1, 0); -- Aarakocra
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (2, 1); -- Aboleth
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (3, 1); -- Ankheg
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (4, 1); -- Arcane
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (5, 1); -- Argos
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (6, 0); -- Aurumvorax
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (7, 0); -- Baatezu, Pit fiend
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (8, 0); -- Baatezu, Black Abishai
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (9, 0); -- Baatezu, Green Abishai
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (10, 0); -- Baatezu, Red Abishai
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (11, NULL); -- Banshee
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (12, 0); -- Basilisk, Lesser
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (13, 0); -- Basilisk, Greater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (14, 0); -- Basilisk, Dracolisk
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (15, 1); -- Bat, Common
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (16, 1); -- Bat, Large
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (17, 1); -- Bat, Huge
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (18, 1); -- Bat, Azmyth
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (19, 0); -- Bat, Night hunter
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (20, 1); -- Bat, Sinister
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (21, 1); -- Bear, Black
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (22, 1); -- Bear, Brown
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (23, 1); -- Bear, Cave
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (24, 1); -- Bear, Polar
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (25, 0); -- Beetle, Giant, Bombardier
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (26, 1); -- Beetle, Giant, Boring
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (27, 1); -- Beetle, Giant, Fire
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (28, 2); -- Beetle, Giant, Rhinoceros
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (29, 2); -- Beetle, Giant, Stag
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (30, 1); -- Beetle, Giant, Water
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (31, 0); -- Behir
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (32, 1); -- Beholder
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (33, 0); -- Beholder, Death kiss
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (34, 1); -- Beholder, Eye of the deep
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (35, 1); -- Beholder, Gauth
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (36, 1); -- Beholder, Spectator
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (37, NULL); -- Beholder, Undead
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (38, 1); -- Beholder, Hive mother
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (39, 1); -- Beholder, Director
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (40, 1); -- Beholder, Examiner
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (41, 4); -- Beholder, Lensman
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (42, 1); -- Beholder, Overseer
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (43, 5); -- Beholder, Watcher
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (44, NULL); -- Beholder, Mage
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (45, NULL); -- Beholder, Elder orb
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (46, NULL); -- Beholder, Orbus
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (47, NULL); -- Beholder, Doomsphere
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (48, NULL); -- Beholder, Kasharin
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (49, NULL); -- Beholder, Astereater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (50, NULL); -- Beholder, Gorbel
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (51, NULL); -- Bird, Blood hawk
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (52, NULL); -- Bird, Boobrie
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (53, NULL); -- Bird, Condor
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (54, NULL); -- Bird, Giant eagle
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (55, NULL); -- Bird, Wild eagle
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (56, NULL); -- Bird, Eblis
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (57, NULL); -- Bird, Emre
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (58, NULL); -- Bird, Falcon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (59, NULL); -- Bird, Flightless bird
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (60, NULL); -- Bird, Large hawk
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (61, NULL); -- Bird, Kingfisher
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (62, NULL); -- Bird, Owl
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (63, NULL); -- Bird, Giant owl
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (64, NULL); -- Bird, Talking owl
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (65, NULL); -- Bird, Raven
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (66, NULL); -- Bird, Huge raven
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (67, NULL); -- Bird, Giant raven
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (68, NULL); -- Bird, Skyfisher
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (69, NULL); -- Bird, Swan
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (70, NULL); -- Bird, Vulture
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (71, NULL); -- Bird, Giant vulture
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (72, 6); -- Brain mole
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (73, NULL); -- Broken one, Common
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (74, NULL); -- Broken one, Greater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (75, 1); -- Brownie
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (75, 5); 
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (76, 1); -- Brownie, Killmoulis
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (76, 5);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (77, 0); -- Bugbear
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (78, 0); -- Bulette
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (79, 0); -- Bullywug
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (80, 0); -- Carrion crawler
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (81, 0); -- Cat, Great, Cheetah
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (82, 0); -- Cat, Great, Jaguar
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (83, 0); -- Cat, Great, Leopard
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (84, 0); -- Cat, Great, Common lion
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (85, 0); -- Cat, Great, Mountain lion
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (86, 0); -- Cat, Great, Spotted lion
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (87, 0); -- Cat, Great, Giant lynx
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (88, 0); -- Cat, Great, Wild tiger
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (89, 0); -- Cat, Great, Smilodon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (90, 0); -- Cat, Small, Domestic
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (91, 0); -- Cat, Small, Wild
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (92, 0); -- Cat, Small, Elven
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (93, 1); -- Catoblepas
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (94, 0); -- Cave fisher
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (95, 1); -- Centaur
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (96, 0); -- Centipede, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (97, 0); -- Centipede, Huge
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (98, 0); -- Centipede, Megalo
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (99, 0); -- Centipede, Tunnel
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (100, 1); -- Chimera
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (101, 1); -- Chimera, Gorgimera
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (102, 0); -- Cloaker
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (103, 1); -- Cockatrice
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (104, 1); -- Cockatrice, Pyrolisk
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (105, 0); -- Couatl
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (106, 1); -- Crabman
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (107, NULL); -- Crawling Claw
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (108, 0); -- Crocodile
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (109, 0); -- Crocodile, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (110, 1); -- Crustacean, Giant crab
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (111, 1); -- Crustacean, Giant crayfish
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (112, NULL); -- Crypt Thing
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (113, NULL); -- Death Knight
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (114, 1); -- Deepspawn
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (115, 2); -- Dinosaur, Ankylosaurus
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (116, 0); -- Dinosaur, Deinonychus
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (117, 2); -- Dinosaur, Diplodocus
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (118, 0); -- Dinosaur, Elasmosaurus
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (119, 2); -- Dinosaur, Lambeosaurus
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (120, 0); -- Dinosaur, Pteranodon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (121, 2); -- Dinosaur, Stegosaurus
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (122, 2); -- Dinosaur, Triceratops
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (123, 0); -- Dinosaur, Tyrannosaurus
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (124, 0); -- Displacer Beast
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (125, 1); -- Dog, Wild dog
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (126, 1); -- Dog, War dog
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (127, 1); -- Dog, Blink dog
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (128, 0); -- Dog, Death dog
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (129, 0); -- Dog, Moon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (130, 0); -- Dolphin
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (131, 1); -- Doppleganger
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (132, NULL); -- Dracolich
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (133, NULL); -- Dragon, Chromatic, Black
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (134, NULL); -- Dragon, Chromatic, Blue
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (135, NULL); -- Dragon, Chromatic, Green'
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (136, NULL); -- Dragon, Chromatic, Red
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (137, NULL); -- Dragon, Chromatic, White
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (138, NULL); -- Dragon, Gem, Amethyst
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (139, NULL); -- Dragon, Gem, Crystal
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (140, NULL); -- Dragon, Gem, Emerald
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (141, NULL); -- Dragon, Gem, Sapphire
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (142, NULL); -- Dragon, Gem, Topaz
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (143, NULL); -- Dragon, Metallic, Brass
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (144, NULL); -- Dragon, Metallic, Bronze
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (145, NULL); -- Dragon, Metallic, Copper
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (146, NULL); -- Dragon, Metallic, Gold
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (147, NULL); -- Dragon, Metallic, Silver
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (148, NULL); -- Brown Dragon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (149, NULL); -- Cloud Dragon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (150, NULL); -- Deep Dragon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (151, NULL); -- Mercury Dragon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (152, NULL); -- Mist Dragon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (153, NULL); -- Shadow Dragon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (154, NULL); -- Steel Dragon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (155, 1); -- Yellow Dragon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (156, 0); -- Dragon turtle
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (157, 2); -- Dragonet, Faerie dragon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (158, 0); -- Dragonet, Firedrake
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (159, 1); -- Dragonet, Pseudodragon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (160, 0); -- Dragonne
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (161, 2); -- Dryad
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (162, 1); -- Dwarf, Hill
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (163, 1); -- Dwarf, Mountain
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (164, 1); -- Dwarf, Derro
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (165, 1); -- Dwarf, Duergar
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (166, 14); -- Elemental, Air
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (167, 16); -- Elemental, Earth
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (167, 17);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (167, 19);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (168, 20); -- Elemental, Fire
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (169, 21); -- Elemental, Water
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (170, 1); -- Elemental, Air Kin, Sylph
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (171, 10); -- Elemental, Air Kin, Aerial servant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (172, 1); -- Elemental, Earth Kin, Pech
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (173, 11); -- Elemental, Earth Kin, Sandling
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (174, 1); -- Elemental, Fire Kin, Salamander
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (175, 12); -- Elemental, Fire Kin, Fire snake
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (176, 13); -- Elemental, Water Kin, Nereid
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (177, NULL); -- Elemental, Water Kin, Water weird
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (178, NULL); -- Elemental, Composite, Tempest
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (179, NULL); -- Elemental, Composite, Skriaxit
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (180, 2); -- Elephant, African
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (181, 2); -- Elephant, Mammoth
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (182, 2); -- Elephant, Mastodon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (183, 2); -- Elephant, Oliphant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (184, 1); -- Elf
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (185, 1); -- Elf, Aquatic
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (186, 1); -- Elf, Drow
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (187, 24); -- Elf, Drider
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (188, 0); -- Ettercap
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (189, NULL); -- Eyewing
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (190, 22); -- Feyr
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (191, 22); -- Great Feyr
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (192, NULL); -- Fish, Barracuda
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (193, NULL); -- Fish, Giant carp
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (194, NULL); -- Fish, Giant catfish
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (195, NULL); -- Fish, Dragonfish
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (196, NULL); -- Fish, Electric eel
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (197, NULL); -- Fish, Giant eel
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (198, NULL); -- Fish, Marine eel
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (199, NULL); -- Fish, Weed eel
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (200, NULL); -- Fish, Giant gar
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (201, NULL); -- Fish, Lamprey
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (202, NULL); -- Fish, Giant lamprey
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (203, NULL); -- Fish, Land lamprey
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (204, NULL); -- Fish, Manta ray
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (205, NULL); -- Fish, Giant pike
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (206, NULL); -- Fish, Piranha
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (207, NULL); -- Fish, Giant piranha
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (208, NULL); -- Fish, Pungi ray
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (209, NULL); -- Fish, Quipper
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (210, NULL); -- Fish, Giant sea horse
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (211, NULL); -- Fish, Shark
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (212, NULL); -- Fish, Giant shark
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (213, NULL); -- Fish, Sting ray
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (214, 0); -- Frog, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (215, 0); -- Frog, Killer
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (216, 4); -- Frog, Poisonous
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (217, 5); -- Fungus, Violet
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (218, 5); -- Fungus, Shrieker
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (219, 5); -- Fungus, Phycomid
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (220, 5); -- Fungus, Ascomoid
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (221, 5); -- Fungus, Gas spore
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (222, 9); -- Galeb Duhr
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (223, 9); -- Gargantua Reptilian
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (224, 1); -- Gargantua Humanoid
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (225, 1); -- Gargantua Insectoid
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (226, 0); -- Gargoyle
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (227, 0); -- Gargoyle, Margoyle
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (228, 1); -- Genie, Djinni
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (229, 1); -- Genie, Dao
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (230, 1); -- Genie, Efreeti
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (231, 1); -- Genie, Marid
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (232, 1); -- Genie, Jann
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (233, NULL); -- Ghost
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (234, 23); -- Ghoul
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (235, 23); -- Ghoul, Lacedon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (236, 23); -- Ghoul, Ghast
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (237, 9); -- Giant, Cloud
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (238, 1); -- Giant, Cyclopskin
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (239, 1); -- Giant, Cyclops
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (240, 1); -- Giant, Desert
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (241, 0); -- Giant, Ettin
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (242, 1); -- Giant, Firbolg
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (243, 1); -- Giant, Fire
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (244, 1); -- Giant, Fog
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (245, 1); -- Giant, Formorian
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (246, 1); -- Giant, Frost
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (247, 1); -- Giant, Hill
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (248, 0); -- Giant, Jungle
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (249, 1); -- Giant, Mountain
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (250, 1); -- Giant, Reef
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (251, 1); -- Giant, Stone
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (252, 1); -- Giant, Storm
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (253, 1); -- Giant, Verbeeg
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (254, 2); -- Giant, Wood
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (255, 0); -- Gibberling
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (256, 1); -- Giff
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (257, 0); -- Gith
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (258, 0); -- Gith, Pirate
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (259, 1); -- Githyanki
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (260, 1); -- Githzerai
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (261, 0); -- Gloomwing
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (262, 0); -- Gloomwing, Tenebrous worm
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (263, 0); -- Gnoll
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (264, 0); -- Gnoll, Flind
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (265, 1); -- Gnome, Rock
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (266, 1); -- Gnome, Svirfneblin
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (267, 1); -- Gnome, Tinker
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (268, 1); -- Gnome, Forest
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (269, 1); -- Gnome, Spriggan
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (270, 0); -- Goblin
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (271, NULL); -- Golem, Greater, Stone
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (272, NULL); -- Golem, Greater, Iron
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (273, NULL); -- Golem, Lesser, Flesh
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (274, NULL); -- Golem, Lesser, Clay
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (275, NULL); -- Golem, Bone
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (276, NULL); -- Golem, Doll
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (277, NULL); -- Golem, Gargoyle
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (278, NULL); -- Golem, Glass
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (279, NULL); -- Golem, Necrophidus
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (280, NULL); -- Golem, Scarecrow
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (281, NULL); -- Golem, Stone Variants, Caryatid column
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (282, NULL); -- Golem, Stone Variants, Juggernaut
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (283, NULL); -- Golem, Stone Variants, Stone guardian
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (284, 0); -- Gorgon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (285, 0); -- Grell Worker
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (286, 0); -- Grell Philosopher
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (287, 0); -- Grell Patriarch
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (288, 1); -- Gremlin
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (289, 2); -- Gremlin, Fremlin
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (290, 24); -- Gremlin, Galltrit
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (291, 1); -- Gremlin, Mite
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (292, 1); -- Gremlin, Snyad
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (293, 1); -- Gremlin, Jermlaine
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (294, 0); -- Griffon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (295, 0); -- Grimlock
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (295, 25); 
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (296, 1); -- Grippli
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (297, 0); -- Hag, Annis
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (298, 0); -- Hag, Green
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (299, 0); -- Hag, Sea
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (300, 1); -- Halfling, Hairfoot
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (301, 1); -- Halfling, Tallfellow
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (302, 1); -- Halfling, Stout
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (303, 0); -- Harpy
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (304, 0); -- Hatori, Lesser
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (305, 0); -- Hatori, Greater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (306, NULL); -- Haunt
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (307, 0); -- Hell Hound
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (308, NULL); -- Heucuva
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (309, 2); -- Hippocampus
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (310, 1); -- Hippogriff
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (311, 1); -- Hobgoblin
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (312, 1); -- Homonculus
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (313, 1); -- Hook Horror
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (314, 2); -- Horse, Draft
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (315, 2); -- Horse, Heavy
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (316, 2); -- Horse, Medium
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (317, 2); -- Horse, Light
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (318, 2); -- Horse, Pony
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (319, 2); -- Horse, Wild
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (320, 2); -- Horse, Riding
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (321, 2); -- Horse, Mule
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (322, NULL); -- Human, Aborigine/Caveman
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (323, NULL); -- Human, Adventurer
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (324, NULL); -- Human, Bandit/Brigand
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (325, NULL); -- Human, Barbarian/Nomad
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (326, NULL); -- Human, Berserker/Dervish
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (327, NULL); -- Human, Farmer/Herder
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (328, NULL); -- Human, Gentry
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (329, NULL); -- Human, Knight
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (330, NULL); -- Human, Mercenary
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (331, NULL); -- Human, Merchant Sailor/Fisherman
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (332, NULL); -- Human, Merchant/Trader
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (333, NULL); -- Human, Middle class
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (334, NULL); -- Human, Peasant/Serf
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (335, NULL); -- Human, Pilgrim
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (336, NULL); -- Human, Pirate/Buccaneer
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (337, NULL); -- Human, Police/Constabulary
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (338, NULL); -- Human, Priest
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (339, NULL); -- Human, Sailor
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (340, NULL); -- Human, Slaver
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (341, NULL); -- Human, Soldier
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (342, NULL); -- Human, Thief/Thug
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (343, NULL); -- Human, Tradesman/Craftsman
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (344, NULL); -- Human, Tribesman
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (345, NULL); -- Human, Wizard
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (346, 0); -- Hydra
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (347, 0); -- Hydra, Lernaean
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (348, 0); -- Hydra, Pyrohydra
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (349, 0); -- Hydra, Cryohydra
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (350, 0); -- Imp
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (351, 0); -- Imp, Quasit
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (352, 9); -- Imp, Mephit, Fire Mephit
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (353, 9); -- Imp, Mephit, Ice Mephit
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (354, 9); -- Imp, Mephit, Lava Mephit
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (355, 9); -- Imp, Mephit, Mist Mephit
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (356, 9); -- Imp, Mephit, Smoke Mephit
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (357, 9); -- Imp, Mephit, Steam Mephit
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (358, NULL); -- Insect, Ant, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (359, NULL); -- Insect, Ant Lion, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (360, NULL); -- Insect, Aratha
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (361, NULL); -- Insect, Aspis, cow
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (362, NULL); -- Insect, Aspis, drone
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (363, NULL); -- Insect, Aspis, larva
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (364, NULL); -- Insect, Assassin Bug
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (365, NULL); -- Insect, Bee, Worker
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (366, NULL); -- Insect, Bee, Soldier
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (367, NULL); -- Insect, Bumblebee
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (368, NULL); -- Insect, Cave cricket
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (369, NULL); -- Insect, Dragonfly, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (370, NULL); -- Insect, Dragonfly, Larva
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (371, NULL); -- Insect, Ear seeker
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (372, NULL); -- Insect, Firefriend
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (373, NULL); -- Insect, Fly, Bluebottle
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (374, NULL); -- Insect, Fly, Horsefly
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (375, NULL); -- Insect, Fyrefly
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (376, NULL); -- Insect, Horax
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (377, NULL); -- Insect, Hornet, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (378, NULL); -- Insect, Pernicon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (379, NULL); -- Insect, Praying Mantis
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (380, NULL); -- Insect, Termite, Giant harvester, King
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (381, NULL); -- Insect, Termite, Giant harvester, Queen
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (382, NULL); -- Insect, Termite, Giant harvester, Soldier
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (383, NULL); -- Insect, Termite, Giant harvester, Worker
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (384, NULL); -- Insect, Tick, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (385, NULL); -- Insect, Wasp, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (386, 1); -- Insect Swarm, Velvet ants swarm
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (387, 2); -- Insect Swarm, Grasshoppers swarm
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (388, 2); -- Insect Swarm, Locust swarm
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (389, 26); -- Intellect devourer, adult
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (390, 22); -- Intellect devourer, larva
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (391, 9); -- Invisible Stalker
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (392, 0); -- Ixitxachitl
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (393, 0); -- Jackalwere
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (394, 1); -- Kenku
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (395, 2); -- Ki-rin
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (396, 0); -- Kirre
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (397, 1); -- Kobold
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (398, 1); -- Kobold, Urd
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (399, 0); -- Kuo-toa
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (400, 0); -- Lamia
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (401, 0); -- Lamia, Noble
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (402, 2); -- Lammasu, Lesser
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (403, 2); -- Lammasu, Greater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (404, 0); -- Leech, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (405, 0); -- Leech, Throat
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (406, 0); -- Leech, Swarm
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (407, 1); -- Leprechaun
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (408, 0); -- Leucrotta
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (409, NULL); -- Lich
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (410, NULL); -- Lich, Demilich
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (411, 27); -- Living Wall
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (412, 0); -- Lizard, Fire
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (413, 0); -- Lizard, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (414, 0); -- Lizard, Minotaur
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (415, 0); -- Lizard, Subterranean
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (416, 9); -- Lizard Man
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (417, 9); -- Lizard Man, King
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (418, 1); -- Locathah
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (419, 1); -- Lurker
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (420, 0); -- Lurker, Trapper
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (421, 0); -- Lurker, Trapper, Forest
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (422, 0); -- Lycanthrope, Seawolf, Lesser
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (423, 0); -- Lycanthrope, Seawolf, Greater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (424, 24); -- Lycanthrope, Werebat
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (425, 1); -- Lycanthrope, Werebear
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (426, 1); -- Lycanthrope, Wereboar
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (427, 0); -- Lycanthrope, Werefox
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (428, 5); -- Lycanthrope, Wererat
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (429, 1); -- Lycanthrope, Wereraven
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (430, 0); -- Lycanthrope, Weretiger
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (431, 0); -- Lycanthrope, Werewolf
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (432, NULL); -- Mammal, Ape, Carnivorous
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (433, NULL); -- Mammal, Baboon, Wild
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (434, NULL); -- Mammal, Badger
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (435, NULL); -- Mammal, Banderlog
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (436, NULL); -- Mammal, Bhaergala
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (437, NULL); -- Mammal, Boar, Wild
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (438, NULL); -- Mammal, Chattur
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (439, NULL); -- Mammal, Cooshee
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (440, NULL); -- Mammal, Dakon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (441, NULL); -- Mammal, Debbi
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (442, NULL); -- Mammal, Goat
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (443, NULL); -- Mammal, Gorilla
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (444, NULL); -- Mammal, Hsing-sing
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (445, NULL); -- Mammal, Hyena
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (446, NULL); -- Mammal, Jackal
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (447, NULL); -- Mammal, Losel
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (448, NULL); -- Mammal, Monkey Spider
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (449, NULL); -- Mammal, Osquip
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (450, NULL); -- Mammal, Porcupine, Black
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (451, NULL); -- Mammal, Porcupine, Brown
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (452, NULL); -- Mammal, Rothe
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (453, NULL); -- Mammal, Skunk
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (454, NULL); -- Mammal, Sleek
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (455, NULL); -- Mammal, Stag, Wild
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (456, NULL); -- Mammal, Stench Kow'
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (457, NULL); -- Mammal, Taer
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (458, NULL); -- Mammal, Tyrg
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (459, NULL); -- Mammal, Warthog
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (460, NULL); -- Mammal, Weasel
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (461, NULL); -- Mammal, Wolverine
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (462, 2); -- Mammal, Herd, Camel
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (463, 2); -- Mammal, Herd, Cattle
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (464, 2); -- Mammal, Herd, Buffalo
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (465, 2); -- Mammal, Herd, Antelope
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (466, 2); -- Mammal, Herd, Sheep
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (467, NULL); -- Mammal, Small, Beaver
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (468, NULL); -- Mammal, Small, Chipmunk
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (469, NULL); -- Mammal, Small, Ermine
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (470, NULL); -- Mammal, Small, Ferret
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (471, NULL); -- Mammal, Small, Fox'
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (472, NULL); -- Mammal, Small, Gopher
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (473, NULL); -- Mammal, Small, Hedgehog
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (474, NULL); -- Mammal, Small, Mink
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (475, NULL); -- Mammal, Small, Mole
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (476, NULL); -- Mammal, Small, Monkey
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (477, NULL); -- Mammal, Small, Mouse
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (478, NULL); -- Mammal, Small, Muskrat
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (479, NULL); -- Mammal, Small, Opossum
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (480, NULL); -- Mammal, Small, Otter
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (481, NULL); -- Mammal, Small, Otter, Sea
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (482, NULL); -- Mammal, Small, Otter, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (483, NULL); -- Mammal, Small, Pig, Domestic
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (484, NULL); -- Mammal, Small, Pig, Wild
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (485, NULL); -- Mammal, Small, Rabbit
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (486, NULL); -- Mammal, Small, Raccoon
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (487, NULL); -- Mammal, Small, Squirrel Flying
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (488, NULL); -- Mammal, Small, Squirrel, Giant Black
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (489, NULL); -- Mammal, Small, Woodchuck
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (490, 0); -- Manscorpion
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (491, 0); -- Manticore
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (492, 1); -- Medusa
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (493, 1); -- Medusa, Greater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (494, 0); -- Maedar
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (495, NULL); -- Maedar, Glyptar
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (496, 1); -- Merman
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (497, 0); -- Mimic
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (498, 0); -- Mimic, Killer Mimic
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (499, 0); -- Mind Flayer
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (499, 28);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (500, 0); -- Minotaur
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (500, 29);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (501, 0); -- Mist, Crimson Death
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (502, 24); -- Mist, Vampiric
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (503, 30); -- Mold, Brown Mold
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (504, 31); -- Mold, Russet Mold
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (505, 26); -- Mold, Yellow Mold
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (506, 0); -- Mold Man
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (507, 1); -- Mongrelman
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (508, 0); -- Morkoth
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (509, 1); -- Muckdweller
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (510, 32); -- Mudman
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (511, NULL); -- Mummy
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (512, NULL); -- Mummy Greater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (513, 2); -- Myconid
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (514, 1); -- Naga, Guardian
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (515, 0); -- Naga, Spirit
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (516, 1); -- Naga, Water
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (517, 0); -- Naga, Dark
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (518, 0); -- Neogi
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (519, 0); -- Neogi, Great Old Master
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (520, 0); -- Nightmare
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (521, NULL); -- Nymph
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (522, 0); -- Octopus giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (523, 0); -- Ogre
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (524, 0); -- Ogre, Mage
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (525, 0); -- Ogre, Merrow
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (526, 1); -- Ogre, Half-Ogre
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (527, 1); -- Ogre, Ogrillion
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (528, 5); -- Ooze, Slime, Jelly, Olive Slime
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (529, 0); -- Ooze, Slime, Jelly, Olive Slime Creature
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (530, 5); -- Ooze, Slime, Jelly, Mustard Jelly
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (531, 5); -- Ooze, Slime, Jelly, Stunjelly
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (532, 1); -- Ooze, Slime, Jelly, Ochre Jelly
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (533, 1); -- Ooze, Slime, Jelly, Gray Ooze
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (534, 1); -- Ooze, Slime, Jelly, Crystal Ooze
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (535, 1); -- Ooze, Slime, Jelly, Gelatinous Cube
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (536, 1); -- Ooze, Slime, Jelly, Green Slime
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (537, 33); -- Ooze, Slime, Jelly, Slithering Tracker
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (538, 0); -- Orc
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (539, 0); -- Orc, Orog
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (540, 1); -- Otyugh
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (541, 1); -- Otyugh, Neo-Otyugh
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (542, 0); -- Owlbear
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (543, 2); -- Pegasus
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (544, 1); -- Peryton
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (545, NULL); -- Phantom
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (546, 1); -- Phoenix
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (547, 0); -- Piercer
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (548, 0); -- Plant, Dangerous, Choke Ceeper
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (549, 0); -- Plant, Dangerous, Mantrap
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (550, 34); -- Plant, Dangerous, Retch Plant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (550, 35);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (551, 0); -- Plant, Dangerous, Snapper Saw
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (552, 0); -- Plant, Dangerous, Thornslinger
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (553, 0); -- Plant, Dangerous, Tri-Flower Frond
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (554, 0); -- Plant, Dangerous, Yellow Musk Creeper
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (555, NULL); -- Plant, Dangerous, Yellow Musk Zombie
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (556, 0); -- Plant, Intelligent, Hangman tree
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (557, 0); -- Plant, Intelligent, Kelpie
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (558, 35); -- Plant, Intelligent, Obliviax
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (558, 18);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (558, 36);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (559, 35); -- Plant, Intelligent, Quickwood
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (559, 18);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (560, 1); -- Plant, Intelligent, Shambling mound
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (561, 0); -- Plant, Intelligent, Strangleweed
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (562, 0); -- Plant, Intelligent, Giant Sundew
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (563, 0); -- Plant, Intelligent, Thorny
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (564, NULL); -- Poltergeist
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (565, 37); -- Pudding, Deadly, Black
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (566, 37); -- Pudding, Deadly, White
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (568, 37); -- Pudding, Deadly, Dun
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (567, 37); -- Pudding, Deadly, Brown
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (569, 0); -- Quaggoth
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (570, 0); -- Rakshasa
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (571, 0); -- Rakshasa, Greater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (572, 5); -- Rat, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (573, 0); -- Rat, Osquip
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (574, 0); -- Remorhaz
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (575, NULL); -- Revenant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (576, 1); -- Roc
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (577, 0); -- Roper
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (578, 38); -- Rust Monster
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (579, 0); -- Sahuagin
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (580, 1); -- Satyr
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (581, 1); -- Satyr, Korred
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (582, 0); -- Scorpion, Large
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (583, 0); -- Scorpion, Huge
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (584, 0); -- Scorpion, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (585, 0); -- Sea Lion
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (586, 1); -- Selkie
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (587, 39); -- Shadow
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (588, 2); -- Shedu, Lesser
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (589, 2); -- Shedu, Greater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (590, 1); -- Sirine
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (591, NULL); -- Skeleton
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (592, NULL); -- Skeleton, Animal
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (593, NULL); -- Skeleton, Monster
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (594, NULL); -- Skeleton, Giant Skeleton
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (595, NULL); -- Skeleton, Warrior
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (596, 0); -- Slaad, Red
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (597, 0); -- Slaad, Blue
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (598, 1); -- Slug, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (599, NULL); -- Snake, Amphisbaena
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (600, NULL); -- Snake, Boalisk
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (601, NULL); -- Snake, Constrictor
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (602, NULL); -- Snake, Giant constrictor
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (603, NULL); -- Snake, Heway
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (604, NULL); -- Snake, Poisonous
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (605, NULL); -- Snake, Giant poisonous
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (606, NULL); -- Snake, Giant sea
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (607, NULL); -- Snake, Spitting
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (608, 2); -- Snake, Winged
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (609, NULL); -- Spectre
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (610, 0); -- Sphinx, Androsphinx
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (611, 0); -- Sphinx, Criosphinx
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (612, 0); -- Sphinx, Gynosphinx
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (613, 0); -- Sphinx, Hieracosphinx
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (614, 1); -- Spider, Hairy
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (615, 0); -- Spider, Large
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (616, 0); -- Spider, Huge
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (617, 0); -- Spider, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (618, 0); -- Spider, Phase
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (619, 0); -- Spider, Sword
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (620, 0); -- Spider, Gargantuan
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (621, 1); -- Sprite', 'Sprite
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (622, 1); -- Sprite, Sea sprite
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (623, 2); -- Sprite, Pixie
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (624, 40); -- Sprite, Nixie
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (625, 2); -- Sprite, Atomie
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (626, 2); -- Sprite, Grig
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (627, 0); -- Squid, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (628, 0); -- Squid, Kraken
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (629, 24); -- Stirge
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (630, 1); -- Su-Monster
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (631, 1); -- Swanmay
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (632, 1); -- Swanmay, Bird maiden
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (633, 0); -- Tabaxi
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (634, 0); -- Tabaxi Lord
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (635, 0); -- Tako, Male
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (636, 0); -- Tako, Female
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (637, 0); -- Tanar''ri, Balor
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (638, 0); -- Tanar''ri, Marilith
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (639, 1); -- Tarrasque
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (640, 1); -- Tasloi
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (641, 26); -- Thought-Eater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (642, 0); -- Thri-Kreen
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (643, 1); -- Titan
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (644, 0); -- Toad, Giant, Giant Toad
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (645, 0); -- Toad, Giant, Fire Toad
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (646, 0); -- Toad, Giant, Ice Toad
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (647, 0); -- Toad, Giant, Poisonous Toad
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (648, 41); -- Treant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (649, 1); -- Triton
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (650, 0); -- Troglodyte
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (651, 0); -- Troll
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (652, 0); -- Troll, Two-headed
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (653, 0); -- Troll, Freshwater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (654, 0); -- Troll, Saltwater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (655, 0); -- Troll, Desert
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (656, 0); -- Troll, Spectral
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (657, 0); -- Troll, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (658, 0); -- Troll, Ice
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (659, NULL); -- Troll, Spirit
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (660, 0); -- Umber Hulk
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (661, 0); -- Umber Hulk, Vodyanoi
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (662, 2); -- Unicorn
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (663, 5); -- Urchin, Black
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (664, 5); -- Urchin, Green
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (665, 5); -- Urchin, Red
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (666, 5); -- Urchin, Silver
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (667, 5); -- Urchin, Yellow
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (668, 5); -- Urchin, Land
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (669, 46); -- Vampire
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (670, 0); -- Wemic
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (671, 42); -- Whale, Common
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (672, 1); -- Whale, Giant
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (673, 1); -- Whale, Leviathan
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (674, 0); -- Whale, Killer
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (675, 40); -- Whale, Narwhal
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (676, 46); -- Wight
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (677, 47); -- Will o''wisp
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (678, 0); -- Wolf
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (679, 0); -- Wolf, Worg
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (680, 0); -- Wolf, Dire
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (681, 0); -- Wolf, Winter
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (682, 0); -- Wolfwere
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (683, 0); -- Worm, Purple
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (684, 24); -- Worm, Giant Bloodworm'
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (685, 43); -- Worm, Bookworm
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (686, 5); -- Worm, Rot Grub
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (687, NULL); -- Wraith
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (688, 0); -- Wyvern
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (689, 11); -- Xorn
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (690, 11); -- Xorn, Xaren
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (690, 44);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (691, 0); -- Yeti
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (692, 0); -- Yuan-ti
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (693, 0); -- Yuan-ti, Histachii
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (694, NULL); -- Yugoloth, Guardian, Least
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (695, NULL); -- Yugoloth, Guardian, Lesser
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (696, NULL); -- Yugoloth, Guardian, Greater
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (697, 1); -- Zaratan
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (698, NULL); -- Zombie
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (699, NULL); -- Zombie, Monster
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (700, NULL); -- Zombie, Ju-ju
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (701, 45); -- Zombie, Lord
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (702, 5); -- Zombie, Sea
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (703, 14); -- Elemental of Chaos, Air, Eolian
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (703, 15);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (704, 16); -- Elemental of Chaos, Earth, Erdeen
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (704, 17);
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (705, 12); -- Elemental of Chaos, Fire, Pyrophor
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (706, 18); -- Elemental of Chaos, Water, Undine
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (707, 5); -- Rat, Common
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (708, 0); -- Slaad, Death
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (709, 0); -- Slaad, Gray
INSERT INTO MONSTER_DIET ([MONSTER_ID], [DIET_ID]) VALUES (710, 0); -- Slaad, Green

COMMIT TRANSACTION;