BEGIN TRANSACTION;

INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (1, 0); -- Aarakocra
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (2, 1); -- Aboleth
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (3, 1); -- Ankheg
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (4, 2); -- Arcane
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (5, 3); -- Argos
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (6, 3); -- Aurumvorax
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (7, 3); -- Pit fiend
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (8, 3); -- Black abishai
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (9, 3); -- Green abishai
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (10, 3); -- Red abishai
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (11, 3); -- Banshee
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (12, 3); -- Lesser basilisk
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (13, 3); -- Greater basilisk
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (14, 3); -- Dracolisk
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (15, 4); -- Common bat
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (16, 5); -- Large bat
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (17, 5); -- Huge bat
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (18, 3); -- Azmyth
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (19, 6); -- Night hunter
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (20, 7); -- Sinister
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (21, 8); -- Black bear
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (22, 8); -- Brown bear
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (23, 8); -- Cave bear
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (24, 8); -- Polar bear
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (25, 3); -- Bombardier
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (26, 3); -- Boring beetle
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (27, 3); -- Fire beetle
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (28, 3); -- Rhinoceros beetle
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (29, 3); -- Stag beetle
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (30, 3); -- Water beetle
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (31, 3); -- Behir
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (32, 3); -- Beholder
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (33, 3); -- Death kiss
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (34, 3); -- Eye of the deep
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (35, 3); -- Gauth
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (36, 3); -- Spectator
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (37, 3); -- Undead beholder
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (38, 3); -- Hive mother
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (39, 9); -- Director
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (40, 9); -- Examiner
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (41, 9); -- Lensman
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (42, 3); -- Overseer
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (43, 3); -- Watcher
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (72, 8); -- Brain mole
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (73, 6); -- Broken one
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (74, 6); -- Greater broken one
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (75, 0); -- Brownie
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (76, 3); -- Killmoulis
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (77, 0); -- Bugbear
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (78, 3); -- Bulette
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (79, 0); -- Bullywug
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (80, 3); -- Carrion crawler
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (81, 10); -- Cheetah
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (82, 3); -- Jaguar
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (83, 3); -- Leopard
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (84, 11); -- Common lion
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (85, 3); -- Mountain lion
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (86, 11); -- Spotted lion
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (87, 3); -- Giant lynx
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (88, 3); -- Wild tiger
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (89, 3); -- Smilodon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (90, 3); -- Domestic cat
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (91, 3); -- Wild cat
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (92, 3); -- Elven cat
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (93, 3); -- Catoblepas
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (94, 12); -- Cave fisher
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (95, 0); -- Centaur
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (99, 4); -- Tunnel centipede
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (101, 3); -- Gorgimera
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (102, 3); -- Cloaker
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (103, 5); -- Cockatrice
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (104, 5); -- Pyrolisk
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (105, 3); -- Couatl
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (106, 0); -- Crabman
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (107, 4); -- Crawling Claw
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (112, 3); -- Crypt Thing
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (113, 3); -- Death Knight
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (114, 3); -- Deepspawn
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (115, 3); -- Ankylosaurus
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (116, 6); -- Deinonychus
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (117, 8); -- Diplodocus
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (118, 3); -- Elasmosaurus
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (119, 13); -- Lambeosaurus
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (120, 5); -- Pteranodon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (121, 13); -- Stegosaurus
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (122, 13); -- Triceratops
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (123, 3); -- Tyrannosaurus
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (124, 6); -- Displacer Beast
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (125, 6); -- Wild dog
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (126, 3); -- War dog
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (127, 6); -- Blink dog
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (128, 6); -- Death dog
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (130, 15); -- Dolphin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (131, 0); -- Doppleganger
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (132, 3); -- Dracolich
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (135, 0); -- Green Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (154, 3); -- Steel Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (155, 3); -- Yellow Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (156, 3); -- Dragon turtle
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (158, 17); -- Firedrake
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (159, 3); -- Pseudodragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (160, 3); -- Dragonne
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (161, 3); -- Dryad
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (162, 16); -- Hill dwarf
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (163, 16); -- Mountain dwarf
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (164, 0); -- Derro
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (165, 0); -- Duergar
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (166, 3); -- Air elemental
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (167, 3); -- Earth elemental
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (168, 3); -- Fire elemental
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (169, 3); -- Water elemental
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (170, 3); -- Sylph
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (171, 3); -- Aerial servant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (172, 16); -- Pech
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (173, 3); -- Sandling
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (174, 6); -- Salamander
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (175, 6); -- Fire Snake
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (176, 3); -- Nereid
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (177, 3); -- Water weird
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (178, 3); -- Tempest
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (179, 6); -- Skriaxit
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (180, 13); -- African elephant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (181, 13); -- Mammoth
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (182, 13); -- Mastodon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (183, 13); -- Oliphant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (184, 7); -- Elf
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (185, 7); -- Aquatic elf
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (187, 7); -- Drider
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (189, 7); -- Eyewing
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (190, 20); -- Feyr
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (191, 3); -- Great Feyr
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (214, 6); -- Giant frog
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (215, 6); -- Killer frog
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (216, 6); -- Poisonous frog
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (217, 21); -- Violet fungus
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (218, 21); -- Shrieker
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (219, 21); -- Phycomid
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (220, 21); -- Ascomoid
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (221, 21); -- Gas spore
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (222, 8); -- Galeb Duhr
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (226, 8); -- Gargoyle
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (227, 8); -- Margoyle
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (228, 23); -- Djinni
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (229, 24); -- Dao
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (230, 25); -- Efreeti
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (231, 26); -- Marid
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (232, 27); -- Jann
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (233, 3); -- Ghost
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (234, 6); -- Ghoul
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (235, 6); -- Lacedon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (236, 6); -- Ghast
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (237, 0); -- Cloud giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (238, 16); -- Cyclopskin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (239, 16); -- Cyclops
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (240, 0); -- Desert giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (241, 3); -- Ettin giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (242, 16); -- Firbolg giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (243, 0); -- Fire giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (245, 3); -- Formorian giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (246, 0); -- Frost giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (247, 0); -- Hill giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (249, 8); -- Mountain giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (250, 3); -- Reef giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (251, 0); -- Stone giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (253, 0); -- Verbeeg giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (254, 16); -- Wood giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (255, 13); -- Gibberling
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (256, 29); -- Giff
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (257, 0); -- Gith
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (261, 3); -- Moth
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (262, 3); -- Tenebrous worm
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (263, 0); -- Gnoll
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (264, 0); -- Flind
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (265, 16); -- Rock gnome
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (266, 34); -- Svirfneblin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (268, 16); -- Forest gnome
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (269, 6); -- Gnome spriggan
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (270, 0); -- Goblin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (271, 3); -- Stone Golem
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (272, 3); -- Iron Golem
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (273, 3); -- Flesh Golem
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (275, 3); -- Bone Golem
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (276, 3); -- Doll Golem
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (277, 3); -- Golem gargoyle
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (278, 3); -- Glass Golem
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (279, 3); -- Golem necrophidus
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (280, 3); -- Scarecrow
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (281, 3); -- Caryatid
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (282, 3); -- Juggernaut
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (283, 3); -- Stone guardian
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (284, 12); -- Gorgon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (285, 36); -- Grell Worker
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (286, 36); -- Grell Philosopher
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (287, 36); -- Grell Patriarch
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (288, 6); -- Gremlin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (289, 6); -- Fremlin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (290, 6); -- Galltrit
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (291, 3); -- Mite
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (292, 8); -- Snyad
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (293, 16); -- Jermlaine
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (294, 11); -- Griffon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (295, 0); -- Grimlock
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (296, 0); -- Grippli
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (297, 37); -- Annis
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (298, 37); -- Green Hag
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (299, 37); -- Sea Hag
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (300, 38); -- Hairfoot
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (301, 38); -- Tallfellow
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (302, 38); -- Stout
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (303, 5); -- Harpy
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (305, 3); -- Greater hatori
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (306, 40); -- Haunt
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (307, 6); -- Hell Hound
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (308, 3); -- Heucuva
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (309, 13); -- Hippocampus
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (310, 13); -- Hippogriff
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (311, 0); -- Hobgoblin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (312, 3); -- Homonculus
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (313, 16); -- Hook Horror
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (314, 13); -- Draft horse
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (315, 13); -- Heavy horse
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (316, 13); -- Medium horse
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (317, 13); -- Light horse
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (318, 13); -- Pony
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (319, 13); -- Wild horse
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (320, 13); -- Riding horse
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (321, 13); -- Mule
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (346, 3); -- Hydra
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (347, 3); -- Lernaean
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (348, 3); -- Pyrohydra
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (349, 3); -- Cryohydra
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (350, 3); -- Imp
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (351, 3); -- Quasit
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (352, 3); -- Fire Mephit
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (353, 3); -- Ice Mephit
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (354, 3); -- Lava Mephit
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (355, 3); -- Mist Mephit
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (356, 3); -- Smoke Mephit
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (357, 3); -- Steam Mephit
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (386, 4); -- Velvet ants swarm
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (387, 4); -- Grasshoppers swarm
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (388, 4); -- Locust swarm
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (389, 3); -- Adult Intellect Devourer
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (390, 3); -- Larva Intellect Devourer
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (391, 3); -- Invisible Stalker
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (392, 0); -- Ixitxachitl
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (393, 6); -- Jackalwere
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (394, 16); -- Kenku
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (395, 3); -- Ki-rin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (396, 6); -- Kirre
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (397, 0); -- Kobold
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (398, 41); -- Urd
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (399, 0); -- Kuo-toa
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (400, 3); -- Lamia
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (401, 3); -- Noble Lamia
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (402, 11); -- Lesser Lammasu
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (404, 12); -- Giant leech
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (405, 12); -- Throat leech
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (406, 4); -- Swarm leech
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (407, 16); -- Leprechaun
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (408, 6); -- Leucrotta
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (409, 3); -- Lich
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (410, 3); -- Demilich
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (411, 3); -- Living Wall
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (412, 3); -- Fire lizard
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (413, 3); -- Giant lizard
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (414, 3); -- Minotaur lizard
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (415, 3); -- Subterranean lizard
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (416, 0); -- Lizard Man
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (417, 0); -- Lizard King
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (418, 16); -- Locathah
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (419, 3); -- Lurker
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (420, 3); -- Trapper
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (421, 3); -- Forest Trapper
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (422, 6); -- Lesser seawolf
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (423, 6); -- Greater seawolf
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (424, 5); -- Werebat
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (425, 3); -- Werebear
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (426, 0); -- Wereboar
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (427, 3); -- Werefox
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (428, 6); -- Wererat
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (429, 5); -- Wereraven
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (430, 3); -- Weretiger
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (431, 6); -- Werewolf
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (462, 13); -- Camel
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (463, 13); -- Cattle
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (464, 13); -- Buffalo
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (465, 13); -- Antelope
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (466, 13); -- Sheep
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (491, 3); -- Manticore
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (492, 3); -- Medusa
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (493, 3); -- Greater Medusa
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (494, 3); -- Maedar
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (495, 3); -- Glyptar
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (496, 38); -- Merman
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (497, 3); -- Mimic
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (498, 3); -- Killer Mimic
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (499, 38); -- Mind Flayer
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (500, 16); -- Minotaur
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (501, 3); -- Crimson Death
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (502, 3); -- Vampiric Mist
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (503, 18); -- Brown Mold
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (504, 18); -- Russet Mold
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (505, 18); -- Yellow Mold
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (506, 0); -- Mold Man
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (507, 0); -- Mongrelman
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (508, 3); -- Morkoth
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (509, 0); -- Muckdweller
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (510, 6); -- Mudman
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (511, 6); -- Mummy
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (512, 3); -- Mummy Greater
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (513, 43); -- Myconid
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (514, 3); -- Guardian Naga
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (515, 3); -- Spirit Naga
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (516, 3); -- Water Naga
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (518, 3); -- Neogi
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (520, 3); -- Nightmare
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (521, 3); -- Nymph
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (522, 3); -- NULL
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (523, 0); -- Ogre
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (524, 0); -- Ogre Mage
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (525, 0); -- Merrow
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (526, 0); -- Half-Ogre
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (527, 0); -- Ogrillion
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (528, 34); -- Olive Slime
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (529, 34); -- Olive Slime Creature
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (530, 3); -- Mustard Jelly
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (531, 3); -- Stunjelly
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (532, 3); -- Ochre Jelly
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (533, 3); -- Gray Ooze
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (534, 3); -- Crystal Ooze
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (535, 3); -- Gelatinous Cube
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (536, 34); -- Green Slime
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (537, 3); -- Slithering Tracker
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (538, 0); -- Orc
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (539, 0); -- Orog
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (540, 3); -- Otyugh
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (541, 3); -- Neo-Otyugh
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (542, 6); -- Owlbear
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (543, 13); -- Pegasus
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (544, 48); -- Peryton
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (545, 3); -- Phantom
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (546, 3); -- Phoenix
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (547, 34); -- Piercer
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (548, 3); -- Choke Creeper
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (549, 19); -- Mantrap
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (550, 49); -- Retch Plant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (551, 3); -- Snapper Saw
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (552, 49); -- Thornslinger
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (553, 50); -- Tri-Flower Frond
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (554, 3); -- Yellow Musk Creeper
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (555, 9); -- Yellow Musk Zombie
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (556, 3); -- Hangman tree
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (557, 3); -- Kelpie
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (558, 34); -- Obliviax
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (559, 3); -- Quickwood
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (560, 3); -- Shambling mound
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (561, 51); -- Strangleweed
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (562, 3); -- Giant Sundew
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (563, 6); -- Thorny
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (564, 12); -- Poltergeist
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (565, 3); -- Black Pudding
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (566, 3); -- White Pudding
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (567, 3); -- Brown Pudding
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (568, 3); -- Dun Pudding
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (569, 0); -- Quaggoth
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (570, 3); -- Rakshasa
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (571, 3); -- Greater Rakshasa
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (572, 6); -- Giant Rat
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (573, 6); -- Osquip
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (574, 3); -- Remorhaz
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (575, 3); -- Revenant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (576, 3); -- Roc
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (577, 3); -- Roper
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (578, 3); -- Rust Monster
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (579, 0); -- Sahuagin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (580, 7); -- Satyr
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (581, 16); -- Korred
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (582, 4); -- Large Scorpion
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (583, 4); -- Huge Scorpion
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (584, 4); -- Giant Scorpion
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (585, 6); -- Sea Lion
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (586, 0); -- Selkie
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (587, 52); -- Shadow
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (588, 13); -- Lesser Shedu
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (589, 53); -- Greater Shedu
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (591, 7); -- Skeleton
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (592, 7); -- Skeleton Animal
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (593, 7); -- Skeleton Monster
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (594, 3); -- Giant Skeleton
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (595, 3); -- Skeleton Warrior
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (596, 12); -- Red Slaad
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (597, 12); -- Blue Slaad
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (598, 3); -- Giant Slug
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (608, 5); -- Winged snake
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (609, 3); -- Spectre
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (610, 3); -- Androsphinx
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (611, 3); -- Criosphinx
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (612, 3); -- Gynosphinx
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (613, 3); -- Hieracosphinx
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (614, 4); -- Hairy Spider
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (615, 4); -- Large Spider
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (616, 6); -- Huge Spider
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (617, 48); -- Giant Spider
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (618, 3); -- Phase Spider
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (619, 3); -- Sword Spider
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (620, 48); -- Gargantuan Spider
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (621, 0); -- Sprite
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (622, 38); -- Sea sprite
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (623, 38); -- Pixie
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (624, 3); -- Nixie
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (625, 3); -- Atomie
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (626, 7); -- Grig
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (627, 3); -- Giant squid
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (628, 3); -- Kraken
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (629, 49); -- Stirge
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (631, 5); -- Swanmay
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (632, 3); -- Bird maiden
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (633, 16); -- Tabaxi
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (635, 0); -- Male Tako
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (636, 0); -- Female Tako
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (637, 3); -- Balor
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (638, 3); -- Marilith
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (639, 3); -- Tarrasque
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (640, 0); -- Tasloi
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (641, 3); -- Thought-Eater
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (642, 6); -- Thri-Kreen
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (643, 12); -- Titan
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (644, 34); -- Giant Toad
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (645, 34); -- Fire Toad
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (646, 34); -- Ice Toad
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (647, 34); -- Poisonous Toad
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (648, 54); -- Treant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (649, 38); -- Triton
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (650, 16); -- Troglodyte
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (651, 12); -- Troll
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (652, 12); -- Two-headed Troll
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (653, 12); -- Freshwater Troll
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (654, 12); -- Saltwater Troll
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (655, 3); -- Desert Troll
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (656, 3); -- Spectral Troll
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (657, 0); -- Giant Troll
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (658, 0); -- Ice Troll
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (660, 3); -- Umber Hulk
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (661, 3); -- Vodyanoi
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (662, 8); -- Unicorn
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (663, 51); -- Black Urchin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (664, 12); -- Green Urchin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (665, 12); -- Red Urchin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (666, 19); -- Silver Urchin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (667, 12); -- Yellow Urchin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (668, 19); -- Land Urchin
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (669, 3); -- Vampire
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (670, 11); -- Wemic
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (671, 55); -- Common Whale
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (672, 19); -- Giant Whale
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (673, 3); -- Leviathan
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (674, 55); -- Killer Whale
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (675, 55); -- Narwhal Whale
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (676, 3); -- Wight
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (677, 3); -- Will o'wisp
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (678, 8); -- Wolf
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (679, 6); -- Worg
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (680, 6); -- Dire Wolf
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (681, 6); -- Winter Wolf
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (682, 3); -- Wolfwere
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (683, 3); -- Purple Worm
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (684, 3); -- Giant Bloodworm
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (685, 3); -- Bookworm
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (686, 4); -- Rot Grub
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (687, 5); -- Wraith
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (688, 3); -- Wyvern
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (689, 3); -- Xorn
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (690, 3); -- Xaren
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (691, 16); -- Yeti
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (693, 0); -- Histachii
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (694, 3); -- Least Yugoloth
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (695, 3); -- Lesser Yugoloth
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (696, 3); -- Greater Yugoloth
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (697, 3); -- Zaratan
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (701, 3); -- Zombie Lord
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (702, 6); -- Sea Zombie

INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (100, 3); -- Chimera
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (100, 11);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (129, 3); -- Mood dog
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (129, 14);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (133, 3); -- Black Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (133, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (134, 3); -- Blue Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (134, 16); 
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (135, 3); -- Green Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (135, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (136, 3); -- Red Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (136, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (137, 3); -- White Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (137, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (138, 3); -- Amethyst Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (138, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (139, 3); -- Crystal Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (139, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (140, 3); -- Emerald Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (140, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (141, 3); -- Sapphire Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (141, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (142, 3); -- Topaz Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (142, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (143, 3); -- Brass Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (143, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (144, 3); -- Bronze Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (144, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (145, 3); -- Copper Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (145, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (146, 3); -- Gold Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (146, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (147, 3); -- Silver Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (147, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (148, 3); -- Brown Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (148, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (149, 3); -- Cloud Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (149, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (150, 3); -- Deep Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (150, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (151, 3); -- Mercury Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (151, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (152, 3); -- Mist Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (152, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (153, 3); -- Shadow Dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (153, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (157, 3); -- Faerie dragon
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (157, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (186, 16); -- Drow
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (186, 7);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (188, 3); -- Ettercap
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (188, 19);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (223, 3); -- Gargantua Reptilian
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (223, 22);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (224, 3); -- Gargantua Humanoid
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (224, 22);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (225, 3); -- Gargantua Insectoid
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (225, 22);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (244, 16); -- Fog giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (244, 28);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (248, 0); -- Jungle giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (248, 57);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (252, 3); -- Storm giant
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (252, 0);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (258, 30); -- Gith pirate
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (258, 31);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (259, 32); -- Githyanki
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (259, 33);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (260, 33); -- Githzerai
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (260, 32);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (267, 34); -- Thinker
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (267, 35);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (304, 3); -- Lesser hatori
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (304, 39);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (403, 3); -- Greater Lammasu
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (403, 11);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (490, 9); -- Manscorpion
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (490, 4);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (490, 42);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (517, 44); -- Dark Naga
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (517, 19);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (517, 3);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (517, 45);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (519, 3); -- Neogi Great Old Master
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (519, 47);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (586, 3); -- Selkie
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (586, 0);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (590, 3); -- Sirine
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (590, 8);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (630, 8); -- Su-Monster
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (630, 16);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (634, 16); -- Tabaxi Lord
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (634, 3);
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (692, 0); -- Yuan-ti
INSERT INTO MONSTER_ORGANISATION ([MONSTER_ID], [ORGANISATION_ID]) VALUES (692, 56); 

COMMIT TRANSACTION;