BEGIN TRANSACTION;

INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (1, 7, NULL); -- Aarakocra
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (2, 4, NULL); -- Aboleth
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (3, 2, 'overall'); -- Ankheg
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (3, 4, 'underside'); -- Ankheg
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (4, 5, 'robed'); -- Arcane
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (4, 3, 'armoured'); -- Arcane
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (5, 0, NULL); -- Argos
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (6, 0, NULL); -- Aurumvorax
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (7, -5, NULL); -- Baatezu, Pit fiend
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (8, 5, NULL); -- Baatezu, Black Abishai
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (9, 3, NULL); -- Baatezu, Green Abishai
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (10, 1, NULL); -- Baatezu, Red Abishai
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (11, 0, NULL); -- Banshee
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (12, 4, NULL); -- Basilisk, Lesser
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (13, 2, NULL); -- Basilisk, Greater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (14, 3, NULL); -- Basilisk, Dracolisk
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (15, 8, NULL); -- Bat, Common
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (16, 8, NULL); -- Bat, Large
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (17, 7, NULL); -- Bat, Huge
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (18, 2, NULL); -- Bat, Azmyth
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (19, 6, NULL); -- Bat, Night hunter
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (20, 3, NULL); -- Bat, Sinister
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (21, 7, NULL); -- Bear, Black
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (22, 6, NULL); -- Bear, Brown
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (23, 6, NULL); -- Bear, Cave
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (24, 6, NULL); -- Bear, Polar
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (25, 4, NULL); -- Beetle, Giant, Bombardier
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (26, 3, NULL); -- Beetle, Giant, Boring
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (27, 4, NULL); -- Beetle, Giant, Fire
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (28, 2, NULL); -- Beetle, Giant, Rhinoceros
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (29, 3, NULL); -- Beetle, Giant, Stag
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (30, 3, NULL); -- Beetle, Giant, Water
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (31, 4, NULL); -- Behir
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (32, 0, NULL); -- Beholder
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (32, 2, NULL); -- Beholder
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (32, 7, NULL); -- Beholder
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (33, 4, NULL); -- Beholder, Death kiss
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (33, 6, NULL); -- Beholder, Death kiss
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (33, 8, NULL); -- Beholder, Death kiss
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (34, 5, NULL); -- Beholder, Eye of the deep
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (35, 0, NULL); -- Beholder, Gauth
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (35, 2, NULL); -- Beholder, Gauth
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (35, 7, NULL); -- Beholder, Gauth
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (36, 4, NULL); -- Beholder, Spectator
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (36, 7, NULL); -- Beholder, Spectator
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (36, 7, NULL); -- Beholder, Spectator
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (37, 0, NULL); -- Beholder, Undead
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (37, 2, NULL); -- Beholder, Undead
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (37, 7, NULL); -- Beholder, Undead
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (38, 0, NULL); -- Beholder, Hive mother
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (39, 2, NULL); -- Beholder, Director
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (39, 4, NULL); -- Beholder, Director
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (40, 5, NULL); -- Beholder, Examiner
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (41, 3, NULL); -- Beholder, Lensman
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (41, 7, NULL); -- Beholder, Lensman
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (42, 2, NULL); -- Beholder, Overseer
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (42, 7, NULL); -- Beholder, Overseer
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (43, 7, NULL); -- Beholder, Watcher
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (46, 10, NULL); -- Beholder, Orbus
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (69, 7, NULL); -- Bird, Swan
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (72, 9, NULL); -- Brain mole
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (73, 7, NULL); -- Broken one, Common
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (73, 10, NULL); -- Broken one, Common
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (74, 5, NULL); -- Broken one, Greater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (74, 8, NULL); -- Broken one, Greater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (75, 3, NULL); -- Brownie
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (76, 6, NULL); -- Brownie, Killmoulis
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (77, 5, NULL); -- Bugbear
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (77, 10, NULL); -- Bugbear
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (78, -2, NULL); -- Bulette
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (78, 4, NULL); -- Bulette
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (78, 6, NULL); -- Bulette
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (79, 6, NULL); -- Bullywug
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (80, 3, NULL); -- Carrion crawler
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (80, 7, NULL); -- Carrion crawler
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (81, 5, NULL); -- Cat, Great, Cheetah
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (82, 6, NULL); -- Cat, Great, Jaguar
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (83, 6, NULL); -- Cat, Great, Leopard
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (84, 5, NULL); -- Cat, Great, Common lion
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (84, 6, NULL); -- Cat, Great, Common lion
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (85, 6, NULL); -- Cat, Great, Mountain lion
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (86, 5, NULL); -- Cat, Great, Spotted lion
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (86, 6, NULL); -- Cat, Great, Spotted lion
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (87, 6, NULL); -- Cat, Great, Giant lynx
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (88, 6, NULL); -- Cat, Great, Wild tiger
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (89, 6, NULL); -- Cat, Great, Smilodon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (90, 6, NULL); -- Cat, Small, Domestic
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (91, 5, NULL); -- Cat, Small, Wild
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (92, 4, NULL); -- Cat, Small, Elven
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (93, 7, NULL); -- Catoblepas
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (94, 4, NULL); -- Cave fisher
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (95, 5, NULL); -- Centaur
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (95, 4, NULL); -- Centaur
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (96, 9, NULL); -- Centipede, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (97, 9, NULL); -- Centipede, Huge
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (98, 5, NULL); -- Centipede, Megalo
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (99, 4, NULL); -- Centipede, Tunnel
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (100, 6, NULL); -- Chimera
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (100, 5, NULL); -- Chimera
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (100, 2, NULL); -- Chimera
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (101, 5, NULL); -- Chimera, Gorgimera
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (101, 2, NULL); -- Chimera, Gorgimera
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (102, 3, NULL); -- Cloaker
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (102, 1, NULL); -- Cloaker
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (103, 6, NULL); -- Cockatrice
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (104, 6, NULL); -- Cockatrice, Pyrolisk
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (105, 5, NULL); -- Couatl
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (106, 4, NULL); -- Crabman
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (107, 7, NULL); -- Crawling Claw
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (108, 5, NULL); -- Crocodile
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (109, 4, NULL); -- Crocodile, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (110, 3, NULL); -- Crustacean, Giant crab
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (111, 4, NULL); -- Crustacean, Giant crayfish
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (112, 3, NULL); -- Crypt Thing
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (113, 0, NULL); -- Death Knight
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (114, 6, NULL); -- Deepspawn
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (115, 0, NULL); -- Dinosaur, Ankylosaurus
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (116, 4, NULL); -- Dinosaur, Deinonychus
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (117, 6, NULL); -- Dinosaur, Diplodocus
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (118, 7, NULL); -- Dinosaur, Elasmosaurus
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (119, 6, NULL); -- Dinosaur, Lambeosaurus
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (120, 7, NULL); -- Dinosaur, Pteranodon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (121, 5, NULL); -- Dinosaur, Stegosaurus
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (122, 2, NULL); -- Dinosaur, Triceratops
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (122, 6, NULL); -- Dinosaur, Triceratops
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (123, 5, NULL); -- Dinosaur, Tyrannosaurus
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (124, 4, NULL); -- Displacer Beast
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (125, 7, NULL); -- Dog, Wild dog
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (126, 6, NULL); -- Dog, War dog
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (127, 5, NULL); -- Dog, Blink dog
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (128, 7, NULL); -- Dog, Death dog
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (129, 0, NULL); -- Dog, Moon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (130, 5, NULL); -- Dolphin
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (131, 5, NULL); -- Doppleganger
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (132, NULL, NULL); -- Dracolich
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (133, 1, NULL); -- Dragon, Chromatic, Black
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (134, 0, NULL); -- Dragon, Chromatic, Blue
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (135, 0, NULL); -- Dragon, Chromatic, Green
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (136, -3, NULL); -- Dragon, Chromatic, Red
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (137, 1, NULL); -- Dragon, Chromatic, White
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (138, -4, NULL); -- Dragon, Gem, Amethyst
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (139, 0, NULL); -- Dragon, Gem, Crystal
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (140, -2, NULL); -- Dragon, Gem, Emerald
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (141, -3, NULL); -- Dragon, Gem, Sapphire
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (142, -1, NULL); -- Dragon, Gem, Topaz
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (143, 0, NULL); -- Dragon, Metallic, Brass
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (144, -2, NULL); -- Dragon, Metallic, Bronze
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (145, 1, NULL); -- Dragon, Metallic, Copper
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (146, -4, NULL); -- Dragon, Metallic, Gold
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (147, -3, NULL); -- Dragon, Metallic, Silver
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (148, 2, NULL); -- Brown Dragon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (149, 0, NULL); -- Cloud Dragon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (150, 0, NULL); -- Deep Dragon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (151, -1, NULL); -- Mercury Dragon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (152, 1, NULL); -- Mist Dragon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (152, -2, NULL); -- Mist Dragon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (153, -4, NULL); -- Shadow Dragon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (154, 0, NULL); -- Steel Dragon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (155, 0, NULL); -- Yellow Dragon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (156, 0, NULL); -- Dragon turtle
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (157, 5, 'visible'); -- Dragonet, Faerie dragon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (157, 1, 'invisible'); -- Dragonet, Faerie dragon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (158, 5, NULL); -- Dragonet, Firedrake
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (159, 2, NULL); -- Dragonet, Pseudodragon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (160, 6, 'flying'); -- Dragonne
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (160, 2, 'ground'); -- Dragonne
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (161, 9, NULL); -- Dryad
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (162, 4, NULL); -- Dwarf, Hill
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (162, 10, NULL); -- Dwarf, Hill
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (163, 4, NULL); -- Dwarf, Mountain
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (163, 10, NULL); -- Dwarf, Mountain
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (164, 5, NULL); -- Dwarf, Derro
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (164, 4, NULL); -- Dwarf, Derro
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (164, 8, NULL); -- Dwarf, Derro
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (166, 2, NULL); -- Elemental, Air
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (167, 2, NULL); -- Elemental, Earth
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (168, 2, NULL); -- Elemental, Fire
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (169, 2, NULL); -- Elemental, Water
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (170, 9, NULL); -- Elemental, Air Kin, Sylph
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (171, 3, NULL); -- Elemental, Air Kin, Aerial servant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (172, 3, NULL); -- Elemental, Earth Kin, Pech
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (173, 3, NULL); -- Elemental, Earth Kin, Sandling
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (174, 5, NULL); -- Elemental, Fire Kin, Salamander
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (174, 3, NULL); -- Elemental, Fire Kin, Salamander
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (175, 6, NULL); -- Elemental, Fire Kin, Fire snake
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (176, 10, NULL); -- Elemental, Water Kin, Nereid
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (177, 4, NULL); -- Elemental, Water Kin, Water weird
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (178, 2, NULL); -- Elemental, Composite, Tempest
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (179, -5, NULL); -- Elemental, Composite, Skriaxit
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (180, 6, NULL); -- Elephant, African
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (181, 5, NULL); -- Elephant, Mammoth
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (182, 6, NULL); -- Elephant, Mastodon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (183, 4, NULL); -- Elephant, Oliphant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (184, 5, NULL); -- Elf
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (184, 10, NULL); -- Elf
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (185, 6, NULL); -- Elf, Aquatic
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (185, 9, NULL); -- Elf, Aquatic
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (186, 4, NULL); -- Elf, Drow
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (186, 10, NULL); -- Elf, Drow
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (187, 3, NULL); -- Elf, Drider
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (188, 6, NULL); -- Ettercap
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (189, 4, NULL); -- Eyewing
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (190, 2, NULL); -- Feyr
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (191, -2, NULL); -- Great Feyr
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (214, 7, NULL); -- Frog, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (215, 8, NULL); -- Frog, Killer
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (216, 8, NULL); -- Frog, Poisonous
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (217, 7, NULL); -- Fungus, Violet
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (218, 7, NULL); -- Fungus, Shrieker
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (219, 5, NULL); -- Fungus, Phycomid
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (220, 3, NULL); -- Fungus, Ascomoid
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (221, 9, NULL); -- Fungus, Gas spore
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (222, -2, NULL); -- Galeb Duhr
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (223, 2, NULL); -- Gargantua Reptilian
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (224, 4, NULL); -- Gargantua Humanoid
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (225, 6, NULL); -- Gargantua Insectoid
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (226, 5, NULL); -- Gargoyle
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (227, 2, NULL); -- Gargoyle, Margoyle
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (228, 4, NULL); -- Genie, Djinni
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (229, 3, NULL); -- Genie, Dao
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (230, 2, NULL); -- Genie, Efreeti
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (231, 0, NULL); -- Genie, Marid
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (232, 2, NULL); -- Genie, Jann
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (232, 5, NULL); -- Genie, Jann
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (233, 0, NULL); -- Ghost
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (233, 8, NULL); -- Ghost
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (234, 6, NULL); -- Ghoul
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (235, 6, NULL); -- Ghoul, Lacedon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (236, 4, NULL); -- Ghoul, Ghast
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (237, 0, NULL); -- Giant, Cloud
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (238, 3, NULL); -- Giant, Cyclopskin
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (239, 2, NULL); -- Giant, Cyclops
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (240, 1, NULL); -- Giant, Desert
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (241, 3, NULL); -- Giant, Ettin
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (242, 2, NULL); -- Giant, Firbolg
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (243, -1, NULL); -- Giant, Fire
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (243, 5, NULL); -- Giant, Fire
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (244, 1, NULL); -- Giant, Fog
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (245, 3, NULL); -- Giant, Formorian
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (246, 0, NULL); -- Giant, Frost
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (246, 5, NULL); -- Giant, Frost
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (247, 3, NULL); -- Giant, Hill
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (247, 5, NULL); -- Giant, Hill
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (248, 3, NULL); -- Giant, Jungle
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (249, 4, NULL); -- Giant, Mountain
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (250, 0, NULL); -- Giant, Reef
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (250, -4, NULL); -- Giant, Reef
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (251, 0, NULL); -- Giant, Stone
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (252, -6, NULL); -- Giant, Storm
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (252, 0, NULL); -- Giant, Storm
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (253, 4, NULL); -- Giant, Verbeeg
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (254, 8, 'natural'); -- Giant, Wood
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (254, 5, 'in armour'); -- Giant, Wood
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (255, 10, NULL); -- Gibberling
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (256, 6, NULL); -- Giff
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (256, 2, NULL); -- Giff
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (257, 8, NULL); -- Gith
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (258, 0, NULL); -- Gith, Pirate
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (259, NULL, NULL); -- Githyanki
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (260, NULL, NULL); -- Githzerai
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (261, 1, NULL); -- Gloomwing, Moth
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (262, 1, NULL); -- Gloomwing, Tenebrous worm
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (263, 5, NULL); -- Gnoll
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (263, 10, NULL); -- Gnoll
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (264, 5, NULL); -- Gnoll, Flind
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (264, 10, NULL); -- Gnoll, Flind
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (265, 6, NULL); -- Gnome, Rock
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (266, 2, NULL); -- Gnome, Svirfneblin
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (267, 10, NULL); -- Gnome, Tinker
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (267, 5, NULL); -- Gnome, Tinker
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (268, 10, NULL); -- Gnome, Forest
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (269, 3, NULL); -- Gnome, Spriggan
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (269, 5, NULL); -- Gnome, Spriggan
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (269, 10, NULL); -- Gnome, Spriggan
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (270, 6, NULL); -- Goblin
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (270, 10, NULL); -- Goblin
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (271, 5, NULL); -- Golem, Greater, Stone
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (272, 3, NULL); -- Golem, Greater, Iron
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (273, 9, NULL); -- Golem, Lesser, Flesh
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (274, 7, NULL); -- Golem, Lesser, Clay
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (275, 0, NULL); -- Golem, Bone
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (276, 4, NULL); -- Golem, Doll
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (277, 0, NULL); -- Golem, Gargoyle
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (278, 4, NULL); -- Golem, Glass
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (279, 2, NULL); -- Golem, Necrophidus
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (280, 6, NULL); -- Golem, Scarecrow
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (281, 5, NULL); -- Golem, Stone Variants, Caryatid column
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (282, 2, NULL); -- Golem, Stone Variants, Juggernaut
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (283, 2, NULL); -- Golem, Stone Variants, Stone guardian
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (284, 2, NULL); -- Gorgon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (285, 5, NULL); -- Grell Worker
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (286, 5, NULL); -- Grell Philosopher
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (286, 0, NULL); -- Grell Philosopher
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (287, -10, NULL); -- Grell Patriarch
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (287, 10, NULL); -- Grell Patriarch
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (288, 4, NULL); -- Gremlin
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (289, 6, NULL); -- Gremlin, Fremlin
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (290, 2, NULL); -- Gremlin, Galltrit
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (291, 8, NULL); -- Gremlin, Mite
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (292, -4, NULL); -- Gremlin, Snyad
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (293, 7, NULL); -- Gremlin, Jermlaine
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (294, 3, NULL); -- Griffon
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (295, 5, NULL); -- Grimlock
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (296, 9, NULL); -- Grippli
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (297, 0, NULL); -- Hag, Annis
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (298, -2, NULL); -- Hag, Green
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (299, 7, NULL); -- Hag, Sea
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (300, 7, NULL); -- Halfling, Hairfoot
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (300, 10, NULL); -- Halfling, Hairfoot
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (301, 6, NULL); -- Halfling, Tallfellow
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (301, 10, NULL); -- Halfling, Tallfellow
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (302, 6, NULL); -- Halfling, Stout
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (302, 10, NULL); -- Halfling, Stout
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (303, 7, NULL); -- Harpy
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (304, 2, NULL); -- Hatori, Lesser
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (305, 1, NULL); -- Hatori, Greater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (306, 0, NULL); -- Haunt
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (307, 4, NULL); -- Hell Hound
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (308, 3, NULL); -- Heucuva
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (309, 5, NULL); -- Hippocampus
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (310, 5, NULL); -- Hippogriff
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (311, 5, NULL); -- Hobgoblin
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (311, 10, NULL); -- Hobgoblin
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (312, 6, NULL); -- Homonculus
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (313, 3, NULL); -- Hook Horror
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (314, 7, NULL); -- Horse, Draft
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (315, 7, NULL); -- Horse, Heavy
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (316, 7, NULL); -- Horse, Medium
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (317, 7, NULL); -- Horse, Light
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (318, 7, NULL); -- Horse, Pony
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (319, 7, NULL); -- Horse, Wild
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (320, 7, NULL); -- Horse, Riding
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (321, 7, NULL); -- Horse, Mule
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (346, 5, NULL); -- Hydra
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (347, 5, NULL); -- Hydra, Lernaean
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (348, 5, NULL); -- Hydra, Pyrohydra
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (349, 5, NULL); -- Hydra, Cryohydra
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (350, 2, NULL); -- Imp
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (351, 2, NULL); -- Imp, Quasit
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (386, 8, NULL); -- Insect Swarm, Velvet ants swarm
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (387, 8, NULL); -- Insect Swarm, Grasshoppers swarm
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (388, 8, NULL); -- Insect Swarm, Locust swarm
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (389, 4, NULL); -- Intellect devourer, adult
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (390, 5, NULL); -- Intellect devourer, larva
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (391, 3, NULL); -- Invisible Stalker
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (392, 6, NULL); -- Ixitxachitl
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (393, 4, NULL); -- Jackalwere
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (394, 5, NULL); -- Kenku
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (395, -5, NULL); -- Ki-rin
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (396, 7, NULL); -- Kirre
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (397, 7, NULL); -- Kobold
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (397, 10, NULL); -- Kobold
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (398, 8, NULL); -- Kobold, Urd
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (399, 4, NULL); -- Kuo-toa
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (400, 3, NULL); -- Lamia
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (401, 3, NULL); -- Lamia, Noble
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (402, 6, NULL); -- Lammasu, Lesser
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (403, 3, NULL); -- Lammasu, Greater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (404, 9, NULL); -- Leech, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (405, 10, NULL); -- Leech, Throat
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (406, 10, NULL); -- Leech, Swarm
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (407, 8, NULL); -- Leprechaun
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (408, 4, NULL); -- Leucrotta
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (409, 0, NULL); -- Lich
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (410, NULL, NULL); -- Lich, Demilich
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (411, 8, NULL); -- Living Wall
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (412, 3, NULL); -- Lizard, Fire
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (413, 5, NULL); -- Lizard, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (414, 5, NULL); -- Lizard, Minotaur
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (415, 5, NULL); -- Lizard, Subterranean
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (416, 5, NULL); -- Lizard Man
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (417, 3, NULL); -- Lizard Man, King
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (418, 6, NULL); -- Locathah
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (419, 6, NULL); -- Lurker
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (420, 3, NULL); -- Lurker, Trapper
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (421, 3, NULL); -- Lurker, Trapper, Forest
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (422, 6, NULL); -- Lycanthrope, Seawolf, Lesser
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (422, 7, NULL); -- Lycanthrope, Seawolf, Lesser
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (423, 5, NULL); -- Lycanthrope, Seawolf, Greater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (424, 5, NULL); -- Lycanthrope, Werebat
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (425, 2, NULL); -- Lycanthrope, Werebear
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (426, 4, NULL); -- Lycanthrope, Wereboar
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (427, 2, NULL); -- Lycanthrope, Werefox
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (427, 4, NULL); -- Lycanthrope, Werefox
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (427, 6, NULL); -- Lycanthrope, Werefox
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (428, 6, NULL); -- Lycanthrope, Wererat
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (429, 6, NULL); -- Lycanthrope, Wereraven
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (430, 3, NULL); -- Lycanthrope, Weretiger
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (431, 5, NULL); -- Lycanthrope, Werewolf
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (462, 7, NULL); -- Mammal, Herd, Camel
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (463, 7, NULL); -- Mammal, Herd, Cattle
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (464, 7, NULL); -- Mammal, Herd, Buffalo
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (465, 7, NULL); -- Mammal, Herd, Antelope
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (466, 7, NULL); -- Mammal, Herd, Sheep
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (490, 5, NULL); -- Manscorpion
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (491, 4, NULL); -- Manticore
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (492, 5, NULL); -- Medusa
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (493, 3, NULL); -- Medusa, Greater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (494, 5, NULL); -- Maedar
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (495, 5, NULL); -- Maedar, Glyptar
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (496, 7, NULL); -- Merman
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (497, 7, NULL); -- Mimic
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (498, 7, NULL); -- Mimic, Killer Mimic
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (499, 5, NULL); -- Mind Flayer
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (500, 6, NULL); -- Minotaur
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (501, 0, NULL); -- Mist, Crimson Death
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (501, 4, NULL); -- Mist, Crimson Death
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (502, 4, 'normal'); -- Mist, Vampiric
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (502, 8, 'when substantial'); -- Mist, Vampiric
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (503, 9, NULL); -- Mold, Brown Mold
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (504, 9, NULL); -- Mold, Russet Mold
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (505, 9, NULL); -- Mold, Yellow Mold
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (506, 4, NULL); -- Mold Man
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (507, 5, NULL); -- Mongrelman
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (508, 3, NULL); -- Morkoth
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (509, 6, NULL); -- Muckdweller
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (510, 10, NULL); -- Mudman
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (511, 3, NULL); -- Mummy
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (512, 2, NULL); -- Mummy Greater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (513, 10, NULL); -- Myconid
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (514, 3, NULL); -- Naga, Guardian
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (515, 4, NULL); -- Naga, Spirit
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (516, 5, NULL); -- Naga, Water
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (517, 6, NULL); -- Naga, Dark
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (518, 3, NULL); -- Neogi
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (519, 5, NULL); -- Neogi, Great Old Master
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (520, -4, NULL); -- Nightmare
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (521, 9, NULL); -- Nymph
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (522, 7, NULL); -- Octopus giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (523, 5, NULL); -- Ogre
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (524, 4, NULL); -- Ogre, Mage
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (525, 4, NULL); -- Ogre, Merrow
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (526, 5, NULL); -- Ogre, Half-Ogre
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (526, 9, NULL); -- Ogre, Half-Ogre
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (527, 6, NULL); -- Ogre, Ogrillion
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (528, 9, NULL); -- Ooze, Slime, Jelly, Olive Slime
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (529, 9, NULL); -- Ooze, Slime, Jelly, Olive Slime Creature
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (530, 4, NULL); -- Ooze, Slime, Jelly, Mustard Jelly
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (531, 8, NULL); -- Ooze, Slime, Jelly, Stunjelly
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (532, 8, NULL); -- Ooze, Slime, Jelly, Ochre Jelly
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (533, 8, NULL); -- Ooze, Slime, Jelly, Gray Ooze
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (534, 8, NULL); -- Ooze, Slime, Jelly, Crystal Ooze
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (535, 8, NULL); -- Ooze, Slime, Jelly, Gelatinous Cube
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (536, 9, NULL); -- Ooze, Slime, Jelly, Green Slime
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (537, 5, NULL); -- Ooze, Slime, Jelly, Slithering Tracker
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (538, 6, NULL); -- Orc
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (538, 10, NULL); -- Orc
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (539, 4, NULL); -- Orc, Orog
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (539, 10, NULL); -- Orc, Orog
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (540, 3, NULL); -- Otyugh
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (541, 0, NULL); -- Otyugh, Neo-Otyugh
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (542, 5, NULL); -- Owlbear
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (543, 6, NULL); -- Pegasus
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (544, 7, NULL); -- Peryton
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (545, NULL, NULL); -- Phantom
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (546, -3, NULL); -- Phoenix
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (547, 3, NULL); -- Piercer
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (548, 6, NULL); -- Plant, Dangerous, Choke Ceeper
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (548, 5, NULL); -- Plant, Dangerous, Choke Ceeper
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (549, 6, NULL); -- Plant, Dangerous, Mantrap
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (550, 8, NULL); -- Plant, Dangerous, Retch Plant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (551, 4, NULL); -- Plant, Dangerous, Snapper Saw
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (551, 7, NULL); -- Plant, Dangerous, Snapper Saw
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (551, 9, NULL); -- Plant, Dangerous, Snapper Saw
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (552, 8, NULL); -- Plant, Dangerous, Thornslinger
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (553, 9, NULL); -- Plant, Dangerous, Tri-Flower Frond
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (554, 7, NULL); -- Plant, Dangerous, Yellow Musk Creeper
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (555, 10, NULL); -- Plant, Dangerous, Yellow Musk Zombie
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (556, 3, NULL); -- Plant, Intelligent, Hangman tree
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (556, 5, NULL); -- Plant, Intelligent, Hangman tree
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (557, 3, NULL); -- Plant, Intelligent, Kelpie
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (558, 10, NULL); -- Plant, Intelligent, Obliviax
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (559, 5, NULL); -- Plant, Intelligent, Quickwood
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (560, 0, NULL); -- Plant, Intelligent, Shambling mound
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (561, 6, NULL); -- Plant, Intelligent, Strangleweed
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (562, 7, NULL); -- Plant, Intelligent, Giant Sundew
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (563, 3, NULL); -- Plant, Intelligent, Thorny
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (564, 10, NULL); -- Poltergeist
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (565, 6, NULL); -- Pudding, Deadly, Black
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (566, 8, NULL); -- Pudding, Deadly, White
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (567, 5, NULL); -- Pudding, Deadly, Brown
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (568, 7, NULL); -- Pudding, Deadly, Dun
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (569, 6, NULL); -- Quaggoth
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (570, -4, NULL); -- Rakshasa
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (571, -5, NULL); -- Rakshasa, Greater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (572, 7, NULL); -- Rat, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (573, 7, NULL); -- Rat, Osquip
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (574, 0, 'overall'); -- Remorhaz
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (574, 2, 'head'); -- Remorhaz
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (574, 4, 'underbelly'); -- Remorhaz
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (575, 10, NULL); -- Revenant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (576, 4, NULL); -- Roc
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (577, 0, NULL); -- Roper
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (578, 2, NULL); -- Rust Monster
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (579, 5, NULL); -- Sahuagin
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (580, 5, NULL); -- Satyr
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (582, 5, NULL); -- Scorpion, Large
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (583, 4, NULL); -- Scorpion, Huge
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (584, 3, NULL); -- Scorpion, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (585, 5, NULL); -- Sea Lion
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (585, 3, NULL); -- Sea Lion
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (586, 5, NULL); -- Selkie
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (586, 10, NULL); -- Selkie
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (587, 7, NULL); -- Shadow
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (588, 4, NULL); -- Shedu, Lesser
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (589, 2, NULL); -- Shedu, Greater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (590, 3, NULL); -- Sirine
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (591, 7, NULL); -- Skeleton
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (592, 8, NULL); -- Skeleton, Animal
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (593, 6, NULL); -- Skeleton, Monster
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (594, 4, NULL); -- Skeleton, Giant Skeleton
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (595, 2, NULL); -- Skeleton, Warrior
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (596, 4, NULL); -- Slaad, Red
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (597, 2, NULL); -- Slaad, Blue
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (598, 8, NULL); -- Slug, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (608, 5, NULL); -- Snake, Winged
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (609, 2, NULL); -- Spectre
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (610, -2, NULL); -- Sphinx, Androsphinx
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (611, 0, NULL); -- Sphinx, Criosphinx
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (612, -1, NULL); -- Sphinx, Gynosphinx
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (613, 1, NULL); -- Sphinx, Hieracosphinx
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (614, 8, NULL); -- Spider, Hairy
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (615, 8, NULL); -- Spider, Large
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (616, 6, NULL); -- Spider, Huge
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (617, 4, NULL); -- Spider, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (618, 7, NULL); -- Spider, Phase
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (619, 3, NULL); -- Spider, Sword
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (620, 4, NULL); -- Spider, Gargantuan
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (621, 6, NULL); -- Sprite
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (622, 6, NULL); -- Sprite, Sea sprite
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (623, 5, NULL); -- Sprite, Pixie
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (624, 7, NULL); -- Sprite, Nixie
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (625, 4, NULL); -- Sprite, Atomie
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (626, 2, NULL); -- Sprite, Grig
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (627, 7, NULL); -- Squid, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (627, 3, NULL); -- Squid, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (628, 5, NULL); -- Squid, Kraken
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (628, 0, NULL); -- Squid, Kraken
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (629, 8, NULL); -- Stirge
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (630, 6, NULL); -- Su-Monster
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (631, 7, NULL); -- Swanmay
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (632, 7, NULL); -- Swanmay, Bird maiden
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (633, 6, NULL); -- Tabaxi
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (634, 3, NULL); -- Tabaxi Lord
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (635, 3, NULL); -- Tako, Male
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (636, 2, NULL); -- Tako, Female
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (637, -8, NULL); -- Tanar'ri, Balor
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (638, -9, NULL); -- Tanar'ri, Marilith
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (639, -3, NULL); -- Tarrasque
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (640, 5, NULL); -- Tasloi
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (640, 6, NULL); -- Tasloi
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (641, 9, NULL); -- Thought-Eater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (642, 5, NULL); -- Thri-Kreen
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (643, 0, NULL); -- Titan
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (644, 6, NULL); -- Toad, Giant, Giant Toad
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (645, 10, NULL); -- Toad, Giant, Fire Toad
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (646, 4, NULL); -- Toad, Giant, Ice Toad
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (647, 7, NULL); -- Toad, Giant, Poisonous Toad
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (648, 0, NULL); -- Treant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (649, 5, NULL); -- Triton
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (650, 5, NULL); -- Troglodyte
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (651, 4, NULL); -- Troll
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (652, 4, NULL); -- Troll, Two-headed
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (653, 4, NULL); -- Troll, Freshwater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (654, 4, NULL); -- Troll, Saltwater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (655, 4, NULL); -- Troll, Desert
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (656, 0, NULL); -- Troll, Spectral
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (657, 4, NULL); -- Troll, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (658, 8, NULL); -- Troll, Ice
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (660, 2, NULL); -- Umber Hulk
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (661, 2, NULL); -- Umber Hulk, Vodyanoi
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (662, 2, NULL); -- Unicorn
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (663, 4, NULL); -- Urchin, Black
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (664, 3, NULL); -- Urchin, Green
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (665, 2, NULL); -- Urchin, Red
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (666, 0, NULL); -- Urchin, Silver
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (667, 1, NULL); -- Urchin, Yellow
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (668, 3, NULL); -- Urchin, Land
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (669, 1, NULL); -- Vampire
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (670, 6, 'male'); -- Wemic
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (670, 5, NULL); -- Wemic
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (670, 7, 'female'); -- Wemic
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (671, 4, NULL); -- Whale, Common
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (672, 3, NULL); -- Whale, Giant
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (673, 1, NULL); -- Whale, Leviathan
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (674, 4, NULL); -- Whale, Killer
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (675, 6, NULL); -- Whale, Narwhal
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (676, 5, NULL); -- Wight
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (677, -8, NULL); -- Will o'wisp
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (678, 7, NULL); -- Wolf
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (679, 6, NULL); -- Wolf, Worg
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (680, 6, NULL); -- Wolf, Dire
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (681, 5, NULL); -- Wolf, Winter
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (682, 3, NULL); -- Wolfwere
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (683, 6, NULL); -- Worm, Purple
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (684, 4, NULL); -- Worm, Giant Bloodworm
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (685, 2, NULL); -- Worm, Bookworm
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (686, 9, NULL); -- Worm, Rot Grub
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (687, 4, NULL); -- Wraith
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (688, 3, NULL); -- Wyvern
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (689, -2, NULL); -- Xorn
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (690, 1, NULL); -- Xorn, Xaren
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (691, 6, NULL); -- Yeti
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (692, 4, NULL); -- Yuan-ti
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (692, 0, NULL); -- Yuan-ti
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (693, 8, NULL); -- Yuan-ti, Histachii
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (694, 3, NULL); -- Yugoloth, Guardian, Least
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (695, 1, NULL); -- Yugoloth, Guardian, Lesser
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (696, -1, NULL); -- Yugoloth, Guardian, Greater
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (697, -6, NULL); -- Zaratan
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (697, 0, NULL); -- Zaratan
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (698, 8, NULL); -- Zombie
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (699, 6, NULL); -- Zombie, Monster
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (700, 6, NULL); -- Zombie, Ju-ju
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (701, 6, NULL); -- Zombie, Lord
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (702, 7, NULL); -- Zombie, Sea
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (707, 7, NULL); -- Rat
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (708, -4, NULL); -- Death Slaad
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (709, -2, NULL); -- Gray Slaad
INSERT INTO MONSTER_AC ([MONSTER_ID], [AC], [AC_VARIANT]) VALUES (710, 0, NULL); -- Green Slaad

END TRANSACTION;