BEGIN TRANSACTION;

INSERT INTO SAVING_THROW ([ID], [DESCRIPTION], [SCORE]) VALUES (0, 'Paralysation', 0);
INSERT INTO SAVING_THROW ([ID], [DESCRIPTION], [SCORE]) VALUES (1, 'Poison', 0);
INSERT INTO SAVING_THROW ([ID], [DESCRIPTION], [SCORE]) VALUES (2, 'Death Magic', 0);
INSERT INTO SAVING_THROW ([ID], [DESCRIPTION], [SCORE]) VALUES (3, 'Rod', 1);
INSERT INTO SAVING_THROW ([ID], [DESCRIPTION], [SCORE]) VALUES (4, 'Staff', 1);
INSERT INTO SAVING_THROW ([ID], [DESCRIPTION], [SCORE]) VALUES (5, 'Wand', 1);
INSERT INTO SAVING_THROW ([ID], [DESCRIPTION], [SCORE]) VALUES (6, 'Petrification', 2);
INSERT INTO SAVING_THROW ([ID], [DESCRIPTION], [SCORE]) VALUES (7, 'Polymorph', 2);
INSERT INTO SAVING_THROW ([ID], [DESCRIPTION], [SCORE]) VALUES (8, 'Breath Weapon', 3);
INSERT INTO SAVING_THROW ([ID], [DESCRIPTION], [SCORE]) VALUES (9, 'Spell', 4);

COMMIT TRANSACTION;

-------------------------------------------------------------------------------------------------------------

BEGIN TRANSACTION;

-- WARRIOR
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 0, 0, 16);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 0, 1, 18);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 0, 2, 17);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 0, 3, 20);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 0, 4, 19);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 1, 0, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 1, 1, 16);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 1, 2, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 1, 3, 17);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 1, 4, 17);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 2, 0, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 2, 1, 16);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 2, 2, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 2, 3, 17);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 2, 4, 17);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 3, 0, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 3, 1, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 3, 2, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 3, 3, 16);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 3, 4, 16);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 4, 0, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 4, 1, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 4, 2, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 4, 3, 16);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 4, 4, 16);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 5, 0, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 5, 1, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 5, 2, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 5, 3, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 5, 4, 14);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 6, 0, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 6, 1, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 6, 2, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 6, 3, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 6, 4, 14);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 7, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 7, 1, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 7, 2, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 7, 3, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 7, 4, 13);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 8, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 8, 1, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 8, 2, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 8, 3, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 8, 4, 13);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 9, 0, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 9, 1, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 9, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 9, 3, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 9, 4, 11);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 10, 0, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 10, 1, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 10, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 10, 3, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 10, 4, 11);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 11, 0, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 11, 1, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 11, 2, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 11, 3, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 11, 4, 10);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 12, 0, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 12, 1, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 12, 2, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 12, 3, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 12, 4, 10);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 13, 0, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 13, 1, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 13, 2, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 13, 3, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 13, 4, 8);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 14, 0, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 14, 1, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 14, 2, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 14, 3, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 14, 4, 8);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 15, 0, 4);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 15, 1, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 15, 2, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 15, 3, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 15, 4, 7);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 16, 0, 4);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 16, 1, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 16, 2, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 16, 3, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 16, 4, 7);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 17, 0, 3);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 17, 1, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 17, 2, 4);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 17, 3, 4);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (1, 17, 4, 6);


-- WIZARD
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 1, 0, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 1, 1, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 1, 2, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 1, 3, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 1, 4, 12);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 2, 0, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 2, 1, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 2, 2, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 2, 3, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 2, 4, 12);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 3, 0, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 3, 1, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 3, 2, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 3, 3, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 3, 4, 12);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 4, 0, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 4, 1, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 4, 2, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 4, 3, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 4, 4, 12);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 5, 0, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 5, 1, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 5, 2, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 5, 3, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 5, 4, 12);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 6, 0, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 6, 1, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 6, 2, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 6, 3, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 6, 4, 10);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 7, 0, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 7, 1, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 7, 2, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 7, 3, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 7, 4, 10);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 8, 0, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 8, 1, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 8, 2, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 8, 3, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 8, 4, 10);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 9, 0, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 9, 1, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 9, 2, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 9, 3, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 9, 4, 10);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 10, 0, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 10, 1, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 10, 2, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 10, 3, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 10, 4, 10);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 11, 0, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 11, 1, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 11, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 11, 3, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 11, 4, 8);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 12, 0, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 12, 1, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 12, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 12, 3, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 12, 4, 8);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 13, 0, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 13, 1, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 13, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 13, 3, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 13, 4, 8);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 14, 0, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 14, 1, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 14, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 14, 3, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 14, 4, 8);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 15, 0, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 15, 1, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 15, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 15, 3, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 15, 4, 8);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 16, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 16, 1, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 16, 2, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 16, 3, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 16, 4, 6);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 17, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 17, 1, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 17, 2, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 17, 3, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 17, 4, 6);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 18, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 18, 1, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 18, 2, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 18, 3, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 18, 4, 6);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 19, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 19, 1, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 19, 2, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 19, 3, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 19, 4, 6);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 20, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 20, 1, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 20, 2, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 20, 3, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 20, 4, 6);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 21, 0, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 21, 1, 3);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 21, 2, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 21, 3, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (2, 21, 4, 4);


-- PRIEST
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 1, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 1, 1, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 1, 2, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 1, 3, 16);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 1, 4, 15);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 2, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 2, 1, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 2, 2, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 2, 3, 16);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 2, 4, 15);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 3, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 3, 1, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 3, 2, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 3, 3, 16);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 3, 4, 15);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 4, 0, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 4, 1, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 4, 2, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 4, 3, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 4, 4, 14);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 5, 0, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 5, 1, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 5, 2, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 5, 3, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 5, 4, 14);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 6, 0, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 6, 1, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 6, 2, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 6, 3, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 6, 4, 14);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 7, 0, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 7, 1, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 7, 2, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 7, 3, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 7, 4, 12);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 8, 0, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 8, 1, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 8, 2, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 8, 3, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 8, 4, 12);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 9, 0, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 9, 1, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 9, 2, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 9, 3, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 9, 4, 12);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 10, 0, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 10, 1, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 10, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 10, 3, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 10, 4, 11);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 11, 0, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 11, 1, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 11, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 11, 3, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 11, 4, 11);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 12, 0, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 12, 1, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 12, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 12, 3, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 12, 4, 11);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 13, 0, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 13, 1, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 13, 2, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 13, 3, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 13, 4, 10);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 14, 0, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 14, 1, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 14, 2, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 14, 3, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 14, 4, 10);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 15, 0, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 15, 1, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 15, 2, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 15, 3, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 15, 4, 10);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 16, 0, 4);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 16, 1, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 16, 2, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 16, 3, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 16, 4, 9);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 17, 0, 4);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 17, 1, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 17, 2, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 17, 3, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 17, 4, 9);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 18, 0, 4);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 18, 1, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 18, 2, 7);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 18, 3, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 18, 4, 9);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 19, 0, 2);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 19, 1, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 19, 2, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 19, 3, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (4, 19, 4, 7);


-- ROGUE
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 1, 0, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 1, 1, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 1, 2, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 1, 3, 16);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 1, 4, 15);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 2, 0, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 2, 1, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 2, 2, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 2, 3, 16);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 2, 4, 15);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 3, 0, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 3, 1, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 3, 2, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 3, 3, 16);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 3, 4, 15);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 4, 0, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 4, 1, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 4, 2, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 4, 3, 16);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 4, 4, 15);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 5, 0, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 5, 1, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 5, 2, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 5, 3, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 5, 4, 13);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 6, 0, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 6, 1, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 6, 2, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 6, 3, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 6, 4, 13);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 7, 0, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 7, 1, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 7, 2, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 7, 3, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 7, 4, 13);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 8, 0, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 8, 1, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 8, 2, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 8, 3, 15);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 8, 4, 13);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 9, 0, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 9, 1, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 9, 2, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 9, 3, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 9, 4, 11);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 10, 0, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 10, 1, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 10, 2, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 10, 3, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 10, 4, 11);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 11, 0, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 11, 1, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 11, 2, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 11, 3, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 11, 4, 11);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 12, 0, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 12, 1, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 12, 2, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 12, 3, 14);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 12, 4, 11);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 13, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 13, 1, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 13, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 13, 3, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 13, 4, 9);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 14, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 14, 1, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 14, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 14, 3, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 14, 4, 9);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 15, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 15, 1, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 15, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 15, 3, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 15, 4, 9);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 16, 0, 10);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 16, 1, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 16, 2, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 16, 3, 13);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 16, 4, 9);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 17, 0, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 17, 1, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 17, 2, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 17, 3, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 17, 4, 7);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 18, 0, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 18, 1, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 18, 2, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 18, 3, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 18, 4, 7);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 19, 0, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 19, 1, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 19, 2, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 19, 3, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 19, 4, 7);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 20, 0, 9);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 20, 1, 6);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 20, 2, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 20, 3, 12);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 20, 4, 7);

INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 21, 0, 8);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 21, 1, 5);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 21, 2, 4);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 21, 3, 11);
INSERT INTO SAVING_THROW_SCORES ([CLASS_TYPE_ID], [LEVEL], [SAVING_THROW_ID], [SCORE]) VALUES (8, 21, 4, 5);

COMMIT TRANSACTION;

-------------------------------------------------------------------------------------------------------------

